/*******************************************************************
 * TobinMUD ver. 1.0 - All rights reserved                         *
 * The TobinMUD Development Team                                   *
 *******************************************************************/
#include "spell_mana.h"

#include <strings.h>

typedef struct {
    const char *name;
    int cost;
} spell_mana_entry_t;

/* Generated by scanning every `new spellInfo(...)` call in
 * sneezymud-master/code/code/misc/spell_info.cc for its name string and
 * MANA_<n> argument, then intersected against Tobin's own Mage/Druid
 * roster (skill.c) -- see spell_mana.h's doc comment. Alphabetical,
 * only the nonzero-cost entries (a MANA_0 spell just falls through to
 * the same default as an unlisted one). */
static const spell_mana_entry_t SPELL_MANA_TABLE[] = {
    { "accelerate", 30 },
    { "acid blast", 53 },
    { "animate", 40 },
    { "arctic blast", 25 },
    { "atomize", 75 },
    { "bind", 50 },
    { "blast of fury", 60 },
    { "blizzard", 50 },
    { "calm", 25 },
    { "chain lightning", 40 },
    { "cloud of concealment", 50 },
    { "color spray", 38 },
    { "conjure elemental air", 40 },
    { "conjure elemental earth", 40 },
    { "conjure elemental fire", 40 },
    { "conjure elemental water", 40 },
    { "copy", 40 },
    { "detect invisibility", 15 },
    { "detect magic", 15 },
    { "dispel invisible", 30 },
    { "dispel magic", 50 },
    { "divination", 35 },
    { "dust storm", 17 },
    { "earthmaw", 10 },
    { "energy drain", 40 },
    { "enhance weapon", 50 },
    { "ensorcer", 40 },
    { "ethereal gate", 50 },
    { "eyes of fertuman", 30 },
    { "faerie fire", 15 },
    { "faerie fog", 20 },
    { "falcon wings", 20 },
    { "farlook", 20 },
    { "fear", 25 },
    { "feathery descent", 25 },
    { "fireball", 33 },
    { "flaming flesh", 20 },
    { "flaming sword", 40 },
    { "flare", 25 },
    { "flight", 30 },
    { "fumble", 35 },
    { "galvanize", 50 },
    { "garmul's tail", 20 },
    { "gills of flesh", 20 },
    { "granite fists", 30 },
    { "gusher", 20 },
    { "gust", 10 },
    { "hands of flame", 20 },
    { "haste", 50 },
    { "hellfire", 47 },
    { "ice storm", 35 },
    { "icy grip", 30 },
    { "identify", 20 },
    { "illuminate", 20 },
    { "immobilize", 20 },
    { "inferno", 54 },
    { "infravision", 20 },
    { "invisibility", 30 },
    { "knot", 200 },
    { "lava lance", 80 },
    { "lava stream", 50 },
    { "levitate", 25 },
    { "lightning bolt", 40 },
    { "mage sight", 25 },
    { "materialize", 15 },
    { "meteor swarm", 40 },
    { "mystic darts", 23 },
    { "pebble spray", 25 },
    { "plasma mirror", 50 },
    { "polymorph", 40 },
    { "powerstone", 25 },
    { "protection from air", 15 },
    { "protection from earth", 15 },
    { "protection from energy", 15 },
    { "protection from fire", 15 },
    { "protection from water", 15 },
    { "sand blast", 35 },
    { "sense life", 15 },
    { "shatter", 40 },
    { "silence", 30 },
    { "sky spirit", 10 },
    { "sling shot", 15 },
    { "slumber", 35 },
    { "spontaneous generation", 35 },
    { "stealth", 20 },
    { "stone skin", 40 },
    { "stunning arrow", 45 },
    { "suffocate", 27 },
    { "telepathy", 20 },
    { "teleport", 25 },
    { "tornado", 23 },
    { "trail seek", 20 },
    { "true sight", 25 },
    { "tsunami", 50 },
    { "watery grave", 40 },
};
#define SPELL_MANA_TABLE_COUNT (int)(sizeof(SPELL_MANA_TABLE) / sizeof(SPELL_MANA_TABLE[0]))

int spell_mana_cost(const char *name, int min_level) {
    if (!name)
        return 10;
    for (int i = 0; i < SPELL_MANA_TABLE_COUNT; i++) {
        if (strcasecmp(name, SPELL_MANA_TABLE[i].name) == 0)
            return SPELL_MANA_TABLE[i].cost;
    }
    /* Fallback for anything not in the real table (a genuine MANA_0
     * entry in the original, or a Tobin-original spell with nothing to
     * look up): a modest level-scaled cost so it's never free, roughly
     * in line with the real data's own low end (level ~1-10 spells run
     * MANA_10-20 there). */
    return 5 + min_level / 2;
}
