/* Originally GENERATED from sneezymud-master spell_num.cc's
 * mapFileToSpellnum(); now hand-maintained (the one-off generator in
 * scratchpad is gone). Maps the raw obj.val2 file-spell-number stored on
 * every ITEM_COMPONENT (type=30) row to its Tobin spell NAME (skill.c). The
 * spell-component binding data itself lives in the obj table (val2=this file
 * number), imported verbatim from real SneezyMUD -- this table just decodes
 * it. The spell NAME here MUST equal skill.c's spell name exactly (the
 * runtime matches with strcasecmp, which is case- but NOT punctuation-
 * insensitive) -- a divergence silently drops the binding and the spell
 * falls back to the generic "any component" gate. When adding a new
 * component or renaming a spell in skill.c, update the matching row here. */

typedef struct { int filenum; const char *spell; } comp_filemap_t;

static const comp_filemap_t COMP_FILEMAP[] = {
    { 0, "gust" },
    { 1, "sling shot" },
    { 2, "gusher" },
    { 3, "hands of flame" },
    { 4, "mystic darts" },
    { 5, "flare" },
    { 6, "sorcerer's globe" },
    { 7, "faerie fire" },
    { 8, "illuminate" },
    { 9, "detect magic" },
    { 10, "stunning arrow" },
    { 11, "materialize" },
    { 12, "protection from earth" },
    { 13, "protection from air" },
    { 14, "protection from fire" },
    { 15, "protection from water" },
    { 16, "protection from energy" },
    { 17, "pebble spray" },
    { 18, "arctic blast" },
    { 19, "color spray" },
    { 20, "infravision" },
    { 21, "identify" },
    { 22, "powerstone" },
    { 23, "faerie fog" },
    { 24, "teleport" },
    { 25, "sense life" },
    { 26, "calm" },
    { 27, "accelerate" },
    { 28, "dust storm" },
    { 29, "levitate" },
    { 30, "feathery descent" },
    { 31, "stealth" },
    { 32, "granite fists" },
    { 33, "icy grip" },
    { 34, "gills of flesh" },
    { 36, "telepathy" },
    { 37, "fear" },
    { 38, "slumber" },
    { 39, "conjure elemental earth" },
    { 40, "conjure elemental air" },
    { 41, "conjure elemental fire" },
    { 42, "conjure elemental water" },
    { 43, "dispel magic" },
    { 44, "enhance weapon" },
    { 45, "galvanize" },
    { 46, "detect invisibility" },
    { 47, "dispel invisible" },
    { 48, "tornado" },
    { 49, "sand blast" },
    { 50, "ice storm" },
    { 51, "blast of fury" },
    { 52, "acid blast" },
    { 53, "fireball" },
    { 54, "farlook" },
    { 55, "falcon wings" },
    { 56, "invisibility" },
    { 57, "ensorcer" },
    { 58, "eyes of fertuman" },
    { 59, "copy" },
    { 60, "haste" },
    { 62, "lightning bolt" },
    { 63, "chain lightning" },
    { 66, "immobilize" },
    { 67, "suffocate" },
    { 68, "flight" },
    { 69, "antigravity" },
    { 73, "divination" },
    { 74, "shatter" },
    { 76, "spontaneous generation" },
    { 80, "meteor swarm" },
    { 81, "lava stream" },
    { 82, "stone skin" },
    { 83, "trail seek" },
    { 86, "lava lance" },
    { 87, "inferno" },
    { 88, "hellfire" },
    { 89, "flaming flesh" },
    { 90, "flaming sword" },
    { 94, "energy drain" },
    { 95, "atomize" },
    { 97, "animate" },
    { 98, "bind" },
    { 99, "ether gate" },
    { 100, "knot" },
    { 102, "fumble" },
    { 103, "mage sight" },
    { 104, "cloud of concealment" },
    { 105, "polymorph" },
    { 106, "silence" },
    { 107, "true sight" },
    { 108, "blizzard" },
    { 110, "watery grave" },
    { 111, "tsunami" },
    { 112, "breath of sarahage" },
    { 113, "plasma mirror" },
    { 114, "Garmul's tail" },
    { 126, "heal light" },
    { 127, "harm light" },
    { 128, "create food" },
    { 129, "create water" },
    { 130, "armor" },
    { 131, "bless" },
    { 132, "clot" },
    { 133, "rain brimstone" },
    { 134, "heal serious" },
    { 135, "harm serious" },
    { 136, "sterilize" },
    { 137, "expel" },
    { 138, "cure disease" },
    { 140, "curse" },
    { 141, "remove curse" },
    { 142, "cure poison" },
    { 143, "heal critical" },
    { 144, "salve" },
    { 145, "poison" },
    { 146, "harm critical" },
    { 147, "infect" },
    { 148, "refresh" },
    { 149, "numb" },
    { 150, "disease" },
    { 151, "flamestrike" },
    { 152, "plague locusts" },
    { 153, "cure blindness" },
    { 154, "summon" },
    { 155, "heal" },
    { 156, "paralyze limb" },
    { 157, "word of recall" },
    { 158, "harm" },
    { 159, "blindness" },
    { 165, "pillar salt" },
    { 166, "earthquake" },
    { 167, "call lightning" },
    { 168, "spontaneous combust" },
    { 178, "bleed" },
    { 179, "paralyze" },
    { 180, "bone breaker" },
    { 181, "wither limb" },
    { 185, "sanctuary" },
    { 186, "cure paralysis" },
    { 187, "second wind" },
    { 192, "heroes feast" },
    { 193, "astral walk" },
    { 194, "portal" },
    { 198, "heal full" },
    { 199, "heal critical spray" },
    { 200, "heal spray" },
    { 201, "heal full spray" },
    { 202, "restore limb" },
    { 203, "knit bone" },
    { 204, "relive" },
    { 205, "crusade" },
    { 206, "consecrate" },
    { 207, "consecrate affect" },
    { 270, "transform limb" },
    { 271, "beast soother" },
    { 273, "root control" },
    { 277, "befriend beast" },
    { 278, "transfix" },
    { 283, "barkskin" },
    { 281, "living vines" },
    { 292, "sticks to snakes" },
    { 293, "stormy skies" },
    { 294, "tree walk" },
    { 298, "beast charm" },
    { 299, "shapeshift" },
    { 323, "aura absolution" },
    { 325, "aura vengeance" },
    { 326, "heal light deikhan" },
    { 328, "armor deikhan" },
    { 329, "bless deikhan" },
    { 332, "expel deikhan" },
    { 333, "clot deikhan" },
    { 335, "sterilize deikhan" },
    { 336, "remove curse deikhan" },
    { 337, "curse deikhan" },
    { 340, "infect deikhan" },
    { 341, "cure disease deikhan" },
    { 342, "create food deikhan" },
    { 343, "create water deikhan" },
    { 344, "heal serious deikhan" },
    { 345, "cure poison deikhan" },
    { 347, "harm serious deikhan" },
    { 348, "poison deikhan" },
    { 350, "heal critical deikhan" },
    { 351, "harm critical deikhan" },
    { 352, "harm light deikhan" },
    { 367, "heroes feast deikhan" },
    { 368, "refresh deikhan" },
    { 369, "synostodweomer" },
    { 374, "salve deikhan" },
    { 379, "harm deikhan" },
    { 380, "numb deikhan" },
    { 384, "aura might" },
    { 386, "aura regeneration" },
    { 388, "aura guardian" },
    { 524, "flatulence" },
    { 525, "boiling blood" },
    { 526, "stupidity" },
    { 527, "celerite" },
    { 528, "deathwave" },
    { 529, "distort" },
    { 530, "soul twist" },
    { 531, "squish" },
    { 532, "coronary" },
    { 533, "legba" },
    { 534, "djalla" },
    { 535, "sense life shaman" },
    { 536, "detect shadow" },
    { 537, "raze" },
    { 538, "intimidate" },
    { 539, "rombler" },
    { 540, "chrism" },
    { 541, "cheval" },
    { 542, "hypnosis" },
    { 543, "lich touch" },
    { 544, "death mist" },
    { 545, "shadow walk" },
    { 546, "clarity" },
    { 548, "aqualung" },
    { 549, "aquatic blast" },
    { 550, "thornflesh" },
    { 551, "enthrall ghoul" },
    { 552, "enthrall ghast" },
    { 553, "enthrall demon" },
    { 554, "enthrall spectre" },
    { 555, "shield of mists" },
    { 556, "create iron golem" },
    { 557, "create diamond golem" },
    { 558, "dancing bones" },
    { 559, "control undead" },
    { 560, "resurrection" },
    { 561, "voodoo" },
    { 563, "vampiric touch" },
    { 564, "life leech" },
    { 566, "create wood golem" },
    { 567, "create rock golem" },
    { 568, "chase spirit" },
    { 569, "cleanse" },
    { 570, "embalm" },
    { 670, "earthmaw" },
    { 671, "creeping doom" },
    { 672, "feral wrath" },
    { 673, "sky spirit" },
    { 687, "healing grasp" },
    { 707, "enliven" },
};
static const int COMP_FILEMAP_COUNT = (int)(sizeof(COMP_FILEMAP)/sizeof(COMP_FILEMAP[0]));
