-- Road-shrink: zone 38. Auto-generated by road_shrink.py.
-- Thins reciprocated degree-2 corridor chains by roughly half;
-- every anchor (junction or external-boundary room) keeps its vnum.
-- Idempotent: repoint UPDATEs setting a value to what it already is,
-- and DELETEs of already-removed rows, are no-ops.

UPDATE roomexit SET destination = 5615 WHERE vnum = 5617 AND direction = 0;
UPDATE roomexit SET destination = 5617 WHERE vnum = 5615 AND direction = 3;
UPDATE roomexit SET destination = 5618 WHERE vnum = 5615 AND direction = 1;
UPDATE roomexit SET destination = 5615 WHERE vnum = 5618 AND direction = 3;
UPDATE roomexit SET destination = 5619 WHERE vnum = 5618 AND direction = 0;
UPDATE roomexit SET destination = 5618 WHERE vnum = 5619 AND direction = 2;

DELETE FROM roomexit WHERE vnum IN (5614,5616);
DELETE FROM room WHERE vnum IN (5614,5616);
