-- Road-shrink: zone 67 (Sidartha - Mountain Road Connector). 2026-08-22.
-- Thins reciprocated degree-2 corridor chains by roughly half; every
-- anchor (junction or external-boundary room) keeps its vnum.
-- 188 -> 161 rooms.
--
-- History note: this is the zone that surfaced the real bug in
-- road_shrink.py's chain-splice logic (fixed same day): the anchor-side
-- (b endpoint) relink used the corridor node's own stored direction
-- instead of looking up the anchor's actual direction back to it, so
-- some anchor exits were never repointed (silent no-op UPDATE, zero
-- rows matched). The first apply attempt caught this via the roomexit
-- -> room foreign key (partial commit: 55 rooms' own exits were
-- deleted, but the FK blocked deleting the room rows since 29 of them
-- still had a stale, unrepointed anchor exit pointing at them). This
-- version is the corrected, complete migration: the same corridor
-- repoints (unaffected by the bug), plus 29 INSERTs restoring the
-- anchor-side reciprocal exit, and a corrected final cut list of the
-- 27 rooms with zero remaining references anywhere. Idempotent
-- throughout.

-- Road-shrink: zone 67. Auto-generated by road_shrink.py.
-- Thins reciprocated degree-2 corridor chains by roughly half;
-- every anchor (junction or external-boundary room) keeps its vnum.
-- Idempotent: repoint UPDATEs setting a value to what it already is,
-- and DELETEs of already-removed rows, are no-ops.
UPDATE roomexit SET destination = 11002 WHERE vnum = 11000 AND direction = 3;
UPDATE roomexit SET destination = 11000 WHERE vnum = 11002 AND direction = 3;
UPDATE roomexit SET destination = 11004 WHERE vnum = 11002 AND direction = 9;
UPDATE roomexit SET destination = 11002 WHERE vnum = 11004 AND direction = 3;
UPDATE roomexit SET destination = 11009 WHERE vnum = 11004 AND direction = 0;
UPDATE roomexit SET destination = 11004 WHERE vnum = 11009 AND direction = 1;
UPDATE roomexit SET destination = 11004 WHERE vnum = 11006 AND direction = 2;
UPDATE roomexit SET destination = 11011 WHERE vnum = 11010 AND direction = 1;
UPDATE roomexit SET destination = 11010 WHERE vnum = 11011 AND direction = 0;
UPDATE roomexit SET destination = 11087 WHERE vnum = 11011 AND direction = 4;
UPDATE roomexit SET destination = 11011 WHERE vnum = 11087 AND direction = 6;
UPDATE roomexit SET destination = 8453 WHERE vnum = 8451 AND direction = 1;
UPDATE roomexit SET destination = 8451 WHERE vnum = 8453 AND direction = 3;
UPDATE roomexit SET destination = 8455 WHERE vnum = 8453 AND direction = 1;
UPDATE roomexit SET destination = 8453 WHERE vnum = 8455 AND direction = 3;
UPDATE roomexit SET destination = 8457 WHERE vnum = 8455 AND direction = 1;
UPDATE roomexit SET destination = 8455 WHERE vnum = 8457 AND direction = 3;
UPDATE roomexit SET destination = 8459 WHERE vnum = 8457 AND direction = 1;
UPDATE roomexit SET destination = 8457 WHERE vnum = 8459 AND direction = 3;
UPDATE roomexit SET destination = 8461 WHERE vnum = 8459 AND direction = 1;
UPDATE roomexit SET destination = 8459 WHERE vnum = 8461 AND direction = 9;
UPDATE roomexit SET destination = 8463 WHERE vnum = 8461 AND direction = 6;
UPDATE roomexit SET destination = 8461 WHERE vnum = 8463 AND direction = 3;
UPDATE roomexit SET destination = 8465 WHERE vnum = 8463 AND direction = 1;
UPDATE roomexit SET destination = 8463 WHERE vnum = 8465 AND direction = 3;
UPDATE roomexit SET destination = 8467 WHERE vnum = 8465 AND direction = 1;
UPDATE roomexit SET destination = 8465 WHERE vnum = 8467 AND direction = 3;
UPDATE roomexit SET destination = 8469 WHERE vnum = 8467 AND direction = 1;
UPDATE roomexit SET destination = 8467 WHERE vnum = 8469 AND direction = 3;
UPDATE roomexit SET destination = 8471 WHERE vnum = 8469 AND direction = 1;
UPDATE roomexit SET destination = 8469 WHERE vnum = 8471 AND direction = 8;
UPDATE roomexit SET destination = 11019 WHERE vnum = 11017 AND direction = 1;
UPDATE roomexit SET destination = 11017 WHERE vnum = 11019 AND direction = 8;
UPDATE roomexit SET destination = 11044 WHERE vnum = 11019 AND direction = 1;
UPDATE roomexit SET destination = 11019 WHERE vnum = 11044 AND direction = 4;
UPDATE roomexit SET destination = 11019 WHERE vnum = 11021 AND direction = 2;
UPDATE roomexit SET destination = 11024 WHERE vnum = 11022 AND direction = 3;
UPDATE roomexit SET destination = 11022 WHERE vnum = 11024 AND direction = 7;
UPDATE roomexit SET destination = 11046 WHERE vnum = 11024 AND direction = 3;
UPDATE roomexit SET destination = 11024 WHERE vnum = 11046 AND direction = 4;
UPDATE roomexit SET destination = 11024 WHERE vnum = 11026 AND direction = 0;
UPDATE roomexit SET destination = 11040 WHERE vnum = 11037 AND direction = 1;
UPDATE roomexit SET destination = 11037 WHERE vnum = 11040 AND direction = 4;
UPDATE roomexit SET destination = 11051 WHERE vnum = 11037 AND direction = 7;
UPDATE roomexit SET destination = 11037 WHERE vnum = 11051 AND direction = 5;
UPDATE roomexit SET destination = 11052 WHERE vnum = 11051 AND direction = 4;
UPDATE roomexit SET destination = 11051 WHERE vnum = 11052 AND direction = 8;
UPDATE roomexit SET destination = 8474 WHERE vnum = 8471 AND direction = 1;
UPDATE roomexit SET destination = 8471 WHERE vnum = 8474 AND direction = 3;
UPDATE roomexit SET destination = 8476 WHERE vnum = 8474 AND direction = 1;
UPDATE roomexit SET destination = 8474 WHERE vnum = 8476 AND direction = 3;
UPDATE roomexit SET destination = 8478 WHERE vnum = 8476 AND direction = 1;
UPDATE roomexit SET destination = 8476 WHERE vnum = 8478 AND direction = 3;
UPDATE roomexit SET destination = 8480 WHERE vnum = 8478 AND direction = 1;
UPDATE roomexit SET destination = 8478 WHERE vnum = 8480 AND direction = 3;
UPDATE roomexit SET destination = 8482 WHERE vnum = 8480 AND direction = 1;
UPDATE roomexit SET destination = 8480 WHERE vnum = 8482 AND direction = 3;
UPDATE roomexit SET destination = 8484 WHERE vnum = 8482 AND direction = 1;
UPDATE roomexit SET destination = 8482 WHERE vnum = 8484 AND direction = 3;
UPDATE roomexit SET destination = 8486 WHERE vnum = 8484 AND direction = 1;
UPDATE roomexit SET destination = 8484 WHERE vnum = 8486 AND direction = 3;
UPDATE roomexit SET destination = 8488 WHERE vnum = 8486 AND direction = 6;
UPDATE roomexit SET destination = 8486 WHERE vnum = 8488 AND direction = 9;
UPDATE roomexit SET destination = 8490 WHERE vnum = 8488 AND direction = 1;
UPDATE roomexit SET destination = 8488 WHERE vnum = 8490 AND direction = 3;
UPDATE roomexit SET destination = 8492 WHERE vnum = 8490 AND direction = 1;
UPDATE roomexit SET destination = 8490 WHERE vnum = 8492 AND direction = 3;
UPDATE roomexit SET destination = 8494 WHERE vnum = 8492 AND direction = 1;
UPDATE roomexit SET destination = 8492 WHERE vnum = 8494 AND direction = 3;
UPDATE roomexit SET destination = 8496 WHERE vnum = 8494 AND direction = 1;
UPDATE roomexit SET destination = 8494 WHERE vnum = 8496 AND direction = 3;
UPDATE roomexit SET destination = 8498 WHERE vnum = 8496 AND direction = 1;
UPDATE roomexit SET destination = 8496 WHERE vnum = 8498 AND direction = 3;
UPDATE roomexit SET destination = 8499 WHERE vnum = 8498 AND direction = 1;
UPDATE roomexit SET destination = 8498 WHERE vnum = 8499 AND direction = 1;
UPDATE roomexit SET destination = 11059 WHERE vnum = 11052 AND direction = 2;
UPDATE roomexit SET destination = 11052 WHERE vnum = 11059 AND direction = 0;
UPDATE roomexit SET destination = 11060 WHERE vnum = 11059 AND direction = 2;
UPDATE roomexit SET destination = 11059 WHERE vnum = 11060 AND direction = 2;
UPDATE roomexit SET destination = 11092 WHERE vnum = 11053 AND direction = 0;
UPDATE roomexit SET destination = 11053 WHERE vnum = 11092 AND direction = 4;
UPDATE roomexit SET destination = 11055 WHERE vnum = 11053 AND direction = 1;
UPDATE roomexit SET destination = 11053 WHERE vnum = 11055 AND direction = 1;
UPDATE roomexit SET destination = 11075 WHERE vnum = 11056 AND direction = 2;
UPDATE roomexit SET destination = 11056 WHERE vnum = 11075 AND direction = 2;
UPDATE roomexit SET destination = 9067 WHERE vnum = 9050 AND direction = 3;
UPDATE roomexit SET destination = 9050 WHERE vnum = 9067 AND direction = 2;
UPDATE roomexit SET destination = 9069 WHERE vnum = 9054 AND direction = 0;
UPDATE roomexit SET destination = 9054 WHERE vnum = 9069 AND direction = 3;
UPDATE roomexit SET destination = 9057 WHERE vnum = 9055 AND direction = 3;
UPDATE roomexit SET destination = 9055 WHERE vnum = 9057 AND direction = 3;
UPDATE roomexit SET destination = 9071 WHERE vnum = 9058 AND direction = 0;
UPDATE roomexit SET destination = 9058 WHERE vnum = 9071 AND direction = 1;
UPDATE roomexit SET destination = 9072 WHERE vnum = 9061 AND direction = 1;
UPDATE roomexit SET destination = 9061 WHERE vnum = 9072 AND direction = 2;
UPDATE roomexit SET destination = 9075 WHERE vnum = 9077 AND direction = 2;
UPDATE roomexit SET destination = 9077 WHERE vnum = 9075 AND direction = 0;
UPDATE roomexit SET destination = 9096 WHERE vnum = 9075 AND direction = 2;
UPDATE roomexit SET destination = 9075 WHERE vnum = 9096 AND direction = 4;
UPDATE roomexit SET destination = 9074 WHERE vnum = 9084 AND direction = 0;
UPDATE roomexit SET destination = 9084 WHERE vnum = 9074 AND direction = 2;
UPDATE roomexit SET destination = 9090 WHERE vnum = 9074 AND direction = 0;
UPDATE roomexit SET destination = 9074 WHERE vnum = 9090 AND direction = 0;
UPDATE roomexit SET destination = 9087 WHERE vnum = 9085 AND direction = 0;
UPDATE roomexit SET destination = 9085 WHERE vnum = 9087 AND direction = 2;
UPDATE roomexit SET destination = 9099 WHERE vnum = 9087 AND direction = 0;
UPDATE roomexit SET destination = 9087 WHERE vnum = 9099 AND direction = 3;
UPDATE roomexit SET destination = 9090 WHERE vnum = 9098 AND direction = 1;
UPDATE roomexit SET destination = 9095 WHERE vnum = 9093 AND direction = 2;
UPDATE roomexit SET destination = 9093 WHERE vnum = 9095 AND direction = 2;

INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (8470, 8, '', '', 0, 0, -1, -1, -1, 8471) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9053, 3, '', '', 0, 0, -1, -1, -1, 9069) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9056, 3, '', '', 0, 0, -1, -1, -1, 9057) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9059, 1, '', '', 0, 0, -1, -1, -1, 9071) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9064, 2, '', '', 0, 0, -1, -1, -1, 9067) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9065, 2, '', '', 0, 0, -1, -1, -1, 9072) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9073, 4, '', '', 0, 0, -1, -1, -1, 9096) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9089, 3, '', '', 0, 0, -1, -1, -1, 9099) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9091, 1, '', '', 0, 0, -1, -1, -1, 9098) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (9094, 2, '', '', 0, 0, -1, -1, -1, 9095) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11001, 3, '', '', 0, 0, -1, -1, -1, 11002) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11003, 3, '', '', 0, 0, -1, -1, -1, 11004) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11007, 2, '', '', 0, 0, -1, -1, -1, 11006) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11008, 1, '', '', 0, 0, -1, -1, -1, 11009) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11012, 6, '', '', 0, 0, -1, -1, -1, 11087) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11018, 8, '', '', 0, 0, -1, -1, -1, 11019) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11020, 2, '', '', 0, 0, -1, -1, -1, 11021) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11023, 7, '', '', 0, 0, -1, -1, -1, 11024) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11025, 0, '', '', 0, 0, -1, -1, -1, 11026) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11039, 4, '', '', 0, 0, -1, -1, -1, 11040) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11043, 4, '', '', 0, 0, -1, -1, -1, 11044) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11045, 4, '', '', 0, 0, -1, -1, -1, 11046) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11047, 0, '', '', 0, 0, -1, -1, -1, 11011) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11054, 1, '', '', 0, 0, -1, -1, -1, 11055) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11057, 2, '', '', 0, 0, -1, -1, -1, 11075) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11064, 4, '', '', 0, 0, -1, -1, -1, 11092) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11080, 8, '', '', 0, 0, -1, -1, -1, 11052) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (11089, 4, '', '', 0, 0, -1, -1, -1, 11074) ON DUPLICATE KEY UPDATE destination = VALUES(destination);

DELETE FROM roomexit WHERE vnum IN (8452,8454,8456,8458,8460,8462,8464,8466,8468,8473,8475,8477,8479,8481,8483,8485,8487,8489,8491,8493,8495,8497,9076,9083,9088,11038,11058);
DELETE FROM room WHERE vnum IN (8452,8454,8456,8458,8460,8462,8464,8466,8468,8473,8475,8477,8479,8481,8483,8485,8487,8489,8491,8493,8495,8497,9076,9083,9088,11038,11058);
