-- Road-shrink: zone 2 (Tobin City Roads). 2026-08-22.
-- Thins reciprocated degree-2 corridor chains by roughly half; every
-- anchor (junction, external-boundary room, or spawn-bearing room per
-- zone_reset/component_placement) keeps its vnum. 413 -> 344 rooms.
--
-- History note: the first version of this migration had a bug (its
-- reciprocity check only looked at each room's own outgoing exits, not
-- one-way inbound exits from OTHER rooms) that wrongly targeted 45 rooms
-- for removal. It was caught immediately by the roomexit->room foreign
-- key on first apply (partial commit: their own exits got deleted, but
-- the room rows survived since the FK blocked the final DELETE). This
-- version is the corrected, complete migration: the same 266 corridor
-- repoints (still correct), plus 43 INSERTs restoring the reciprocal
-- exit for every room that should never have been cut (2 more -- 104,
-- 167 -- are legitimate one-way portal targets from zone 106 with no
-- zone-2-side reciprocal to restore; they keep their vnum but currently
-- have no outgoing exit, flagged for a manual redit follow-up), and a
-- corrected final cut list of the 69 rooms that truly have zero
-- remaining references anywhere. Idempotent throughout: UPDATEs setting
-- a value to what it already is, INSERTs with ON DUPLICATE KEY UPDATE,
-- and DELETEs of already-removed rows are all no-ops on replay.

-- Road-shrink: zone 2. Auto-generated by road_shrink.py.
-- Thins reciprocated degree-2 corridor chains by roughly half;
-- every anchor (junction or external-boundary room) keeps its vnum.
-- Idempotent: repoint UPDATEs setting a value to what it already is,
-- and DELETEs of already-removed rows, are no-ops.
UPDATE roomexit SET destination = 353 WHERE vnum = 103 AND direction = 0;
UPDATE roomexit SET destination = 103 WHERE vnum = 353 AND direction = 0;
UPDATE roomexit SET destination = 111 WHERE vnum = 108 AND direction = 1;
UPDATE roomexit SET destination = 108 WHERE vnum = 111 AND direction = 1;
UPDATE roomexit SET destination = 126 WHERE vnum = 111 AND direction = 0;
UPDATE roomexit SET destination = 111 WHERE vnum = 126 AND direction = 2;
UPDATE roomexit SET destination = 127 WHERE vnum = 126 AND direction = 7;
UPDATE roomexit SET destination = 126 WHERE vnum = 127 AND direction = 7;
UPDATE roomexit SET destination = 148 WHERE vnum = 122 AND direction = 0;
UPDATE roomexit SET destination = 122 WHERE vnum = 148 AND direction = 2;
UPDATE roomexit SET destination = 145 WHERE vnum = 148 AND direction = 6;
UPDATE roomexit SET destination = 148 WHERE vnum = 145 AND direction = 6;
UPDATE roomexit SET destination = 211 WHERE vnum = 122 AND direction = 2;
UPDATE roomexit SET destination = 122 WHERE vnum = 211 AND direction = 2;
UPDATE roomexit SET destination = 359 WHERE vnum = 166 AND direction = 1;
UPDATE roomexit SET destination = 166 WHERE vnum = 359 AND direction = 1;
UPDATE roomexit SET destination = 169 WHERE vnum = 166 AND direction = 2;
UPDATE roomexit SET destination = 166 WHERE vnum = 169 AND direction = 2;
UPDATE roomexit SET destination = 189 WHERE vnum = 185 AND direction = 1;
UPDATE roomexit SET destination = 185 WHERE vnum = 189 AND direction = 3;
UPDATE roomexit SET destination = 193 WHERE vnum = 189 AND direction = 6;
UPDATE roomexit SET destination = 189 WHERE vnum = 193 AND direction = 9;
UPDATE roomexit SET destination = 195 WHERE vnum = 193 AND direction = 6;
UPDATE roomexit SET destination = 193 WHERE vnum = 195 AND direction = 6;
UPDATE roomexit SET destination = 204 WHERE vnum = 185 AND direction = 3;
UPDATE roomexit SET destination = 185 WHERE vnum = 204 AND direction = 3;
UPDATE roomexit SET destination = 221 WHERE vnum = 218 AND direction = 2;
UPDATE roomexit SET destination = 218 WHERE vnum = 221 AND direction = 2;
UPDATE roomexit SET destination = 380 WHERE vnum = 370 AND direction = 1;
UPDATE roomexit SET destination = 370 WHERE vnum = 380 AND direction = 4;
UPDATE roomexit SET destination = 385 WHERE vnum = 374 AND direction = 4;
UPDATE roomexit SET destination = 374 WHERE vnum = 385 AND direction = 4;
UPDATE roomexit SET destination = 381 WHERE vnum = 378 AND direction = 3;
UPDATE roomexit SET destination = 378 WHERE vnum = 381 AND direction = 4;
UPDATE roomexit SET destination = 860 WHERE vnum = 856 AND direction = 6;
UPDATE roomexit SET destination = 856 WHERE vnum = 860 AND direction = 9;
UPDATE roomexit SET destination = 862 WHERE vnum = 860 AND direction = 6;
UPDATE roomexit SET destination = 860 WHERE vnum = 862 AND direction = 6;
UPDATE roomexit SET destination = 868 WHERE vnum = 864 AND direction = 0;
UPDATE roomexit SET destination = 864 WHERE vnum = 868 AND direction = 0;
UPDATE roomexit SET destination = 875 WHERE vnum = 871 AND direction = 0;
UPDATE roomexit SET destination = 871 WHERE vnum = 875 AND direction = 8;
UPDATE roomexit SET destination = 879 WHERE vnum = 875 AND direction = 7;
UPDATE roomexit SET destination = 875 WHERE vnum = 879 AND direction = 8;
UPDATE roomexit SET destination = 883 WHERE vnum = 879 AND direction = 7;
UPDATE roomexit SET destination = 879 WHERE vnum = 883 AND direction = 3;
UPDATE roomexit SET destination = 893 WHERE vnum = 889 AND direction = 3;
UPDATE roomexit SET destination = 889 WHERE vnum = 893 AND direction = 6;
UPDATE roomexit SET destination = 897 WHERE vnum = 893 AND direction = 9;
UPDATE roomexit SET destination = 893 WHERE vnum = 897 AND direction = 6;
UPDATE roomexit SET destination = 901 WHERE vnum = 897 AND direction = 9;
UPDATE roomexit SET destination = 897 WHERE vnum = 901 AND direction = 2;
UPDATE roomexit SET destination = 911 WHERE vnum = 907 AND direction = 2;
UPDATE roomexit SET destination = 907 WHERE vnum = 911 AND direction = 7;
UPDATE roomexit SET destination = 915 WHERE vnum = 911 AND direction = 8;
UPDATE roomexit SET destination = 911 WHERE vnum = 915 AND direction = 7;
UPDATE roomexit SET destination = 919 WHERE vnum = 915 AND direction = 8;
UPDATE roomexit SET destination = 915 WHERE vnum = 919 AND direction = 3;
UPDATE roomexit SET destination = 921 WHERE vnum = 919 AND direction = 1;
UPDATE roomexit SET destination = 919 WHERE vnum = 921 AND direction = 1;

INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (102, 1, '', '', 0, 0, -1, -1, -1, 103) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (113, 3, '', '', 0, 0, -1, -1, -1, 114) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (121, 3, '', '', 0, 0, -1, -1, -1, 122) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (128, 7, '', '', 0, 0, -1, -1, -1, 129) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (133, 3, '', '', 0, 0, -1, -1, -1, 134) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (136, 3, '', '', 0, 0, -1, -1, -1, 137) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (142, 9, '', '', 0, 0, -1, -1, -1, 143) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (160, 1, '', '', 0, 0, -1, -1, -1, 161) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (171, 0, '', '', 0, 0, -1, -1, -1, 172) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (176, 2, '', '', 0, 0, -1, -1, -1, 177) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (178, 2, '', '', 0, 0, -1, -1, -1, 179) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (183, 2, '', '', 0, 0, -1, -1, -1, 184) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (198, 0, '', '', 0, 0, -1, -1, -1, 199) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (205, 7, '', '', 0, 0, -1, -1, -1, 206) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (229, 2, '', '', 0, 0, -1, -1, -1, 230) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (231, 2, '', '', 0, 0, -1, -1, -1, 232) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (233, 2, '', '', 0, 0, -1, -1, -1, 234) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (237, 1, '', '', 0, 0, -1, -1, -1, 238) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (242, 0, '', '', 0, 0, -1, -1, -1, 241) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (243, 2, '', '', 0, 0, -1, -1, -1, 244) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (248, 2, '', '', 0, 0, -1, -1, -1, 249) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (259, 3, '', '', 0, 0, -1, -1, -1, 258) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (262, 2, '', '', 0, 0, -1, -1, -1, 296) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (274, 2, '', '', 0, 0, -1, -1, -1, 278) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (277, 2, '', '', 0, 0, -1, -1, -1, 281) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (283, 1, '', '', 0, 0, -1, -1, -1, 284) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (307, 2, '', '', 0, 0, -1, -1, -1, 308) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (312, 2, '', '', 0, 0, -1, -1, -1, 313) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (325, 2, '', '', 0, 0, -1, -1, -1, 326) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (332, 2, '', '', 0, 0, -1, -1, -1, 333) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (352, 0, '', '', 0, 0, -1, -1, -1, 355) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (356, 0, '', '', 0, 0, -1, -1, -1, 359) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (365, 2, '', '', 0, 0, -1, -1, -1, 368) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (375, 2, '', '', 0, 0, -1, -1, -1, 378) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (401, 2, '', '', 0, 0, -1, -1, -1, 402) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (416, 0, '', '', 0, 0, -1, -1, -1, 422) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (560, 7, '', '', 0, 0, -1, -1, -1, 238) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (807, 3, '', '', 0, 0, -1, -1, -1, 806) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (816, 0, '', '', 0, 0, -1, -1, -1, 813) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (850, 4, '', '', 0, 0, -1, -1, -1, 851) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (884, 3, '', '', 0, 0, -1, -1, -1, 886) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (902, 2, '', '', 0, 0, -1, -1, -1, 904) ON DUPLICATE KEY UPDATE destination = VALUES(destination);
INSERT INTO roomexit (vnum, direction, name, description, type, condition_flag, lock_difficulty, weight, key_num, destination) VALUES (920, 4, '', '', 0, 0, -1, -1, -1, 921) ON DUPLICATE KEY UPDATE destination = VALUES(destination);

DELETE FROM roomexit WHERE vnum IN (109,115,123,125,138,140,147,149,151,186,188,190,192,194,196,201,203,208,210,212,214,219,246,252,315,321,324,327,329,350,354,366,371,377,383,386,413,417,420,815,821,853,855,857,859,861,863,865,870,872,874,876,878,880,882,888,890,892,894,896,898,900,906,908,910,912,914,916,918);
DELETE FROM room WHERE vnum IN (109,115,123,125,138,140,147,149,151,186,188,190,192,194,196,201,203,208,210,212,214,219,246,252,315,321,324,327,329,350,354,366,371,377,383,386,413,417,420,815,821,853,855,857,859,861,863,865,870,872,874,876,878,880,882,888,890,892,894,896,898,900,906,908,910,912,914,916,918);
