-- Per-skill/spell help topics (user 2026-07-18: "also no spell
-- helpfiles? that was my instruction. help files for all skills/spells
-- along with required components" -- a correction: the earlier
-- inline-note-in-`skills` approach was NOT what was asked for, this
-- generates a real `help <name>` topic for every entry in skill.c's
-- SKILLS[] roster instead). Machine-generated -- a one-shot Python
-- script (not committed to the repo; regenerate by hand if skill.c's
-- roster changes significantly) parsed SKILLS[]'s own
-- name/class/tier/level/description fields directly, so this can't
-- drift out of sync with the roster by hand-transcription error.
-- One row per unique skill/spell NAME (25 names are shared across more
-- than one class -- mostly identical weapon-proficiency rows, plus a
-- handful of same-named Cleric/Druid prayers-and-spells like "cure
-- poison" -- merged into a single topic listing every class that has
-- it, rather than colliding on help_topic's `name` primary key).
--
-- REDESIGNED 2026-07-22 (user wireframe, using "gust" as the worked
-- example): a real `Usage: cast/pray <name> [<target>]` leading line
-- (parsed by cmd_help.c's existing generic Usage-stripping logic, same
-- as any real command topic) whenever the spell is cast/pray-reachable
-- -- omitted for still-placeholder physical skills, which have nothing
-- to show; a bare `Classes:` list with NO tier/level parenthetical
-- (that number now lives in the new `Approx. Level:` footer instead);
-- `Requires:` names the REAL specific reagent a spell traditionally
-- used, for every spell the upstream source actually assigned one to.
-- Two follow-up asks drove this to its final form: (1) "this should
-- list the actual component required for the spell" -- first pass used
-- `obj/obj_component.h`'s `const int COMP_<SPELL> = <vnum>;` table (56
-- matches); (2) "is there a list of components to spells from the code
-- we could map" -- yes, a far more complete one: `misc/spell_num.cc`'s
-- `mapFileToSpellnum()` (~500 entries, file_to_spell.py) maps every
-- component object's raw file-format "value 3" field -- which Tobin's
-- own `obj.val2` preserves verbatim -- to its real spell. This
-- generator now queries EVERY real "component"-keyword row in Tobin's
-- own seeded `obj` table live, joins each one's `val2` through that
-- table, and keeps the lowest-vnum match per spell (same "lowest vnum
-- wins" precedent the original's own `CompInfo.comp_num` tracking
-- uses) -- far more real matches than the original 56-entry hand
-- curation, and confirmed live against Tobin's real seeded rows, not
-- guessed. Every OTHER Mage/Druid spell (the upstream never assigned
-- these one either) keeps the honest generic phrasing (`a pouch of
-- spell components` -- a real, commonly-seeded row, not a one-off)
-- rather than fabricating a specific item. Cleric's holy-symbol
-- Requires stays generic throughout (`a wooden holy symbol`) -- the
-- upstream's own component system is Wizardry/material-reagent-
-- specific, Ritualism's holy symbols were never assigned individual
-- per-prayer items the same way. A new `Discipline:` footer line
-- (skill/spell topics only, shown only when the upstream source
-- actually has one) reports the real `misc/spell_info.cc`
-- `discArray[]` `start` value -- a genuine 0-100 threshold against
-- that spell's OWN discipline track in the original (user: "along with
-- the % of discipline needed to gain the spell/skill"). Shown as-is,
-- per the user's own explicit choice when asked how to reconcile it
-- with Tobin's simplified single basic_disc_pct/advanced_disc_pct pair
-- (the original splits casters into several separate per-school
-- disciplines -- Air/Fire/Water/Mage/Ritualism/... -- that Tobin
-- collapsed into one each; a shown "Discipline: 26%" is against that
-- spell's own unported discipline, not literally Tobin's own
-- basic_disc_pct). The description
-- itself is auto-elaborated with a targeting sentence (area-effect vs.
-- single-target vs. self-only vs. "not wired to a real effect yet"),
-- derived from EXACTLY the same substring categorization cmd_cast.c's
-- task_cast() itself uses to dispatch the real effect, so the help
-- text can never silently drift out of sync with what a spell actually
-- does. A name that's already a real dispatch-table command (disarm,
-- riding -> `ride`, sign -> `sign`, steal, peek, repair, the set-trap
-- variants -> `settrap`, disarm trap -> `disarmtrap`, ...) generates a
-- row that says so plainly -- inert in practice, since help_topic.sql's
-- own real entry for that name is applied first and wins (`ON DUPLICATE
-- KEY UPDATE name=name` is a no-op on the second insert), but accurate
-- rather than misleading if anyone ever reads this file directly.
-- "disease" is deliberately EXCLUDED here -- it collides with an
-- existing general-mechanic topic (drink a puddle -> catch a disease --
-- see below) that predates this session's Cleric "disease" prayer;
-- handled by hand-appending to that existing topic instead of fighting
-- over one name.
INSERT INTO `help_topic` (`name`, `body`, `updated_by`) VALUES
('accelerate', 'Usage: cast accelerate [<target>]\n\nA group buff that speeds everyone up. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the hindpaw from a greyhound\nRelated: skills practice cast pray affects\nApprox. Level: 11\nDiscipline: 32%\nClasses: Mage', 'seed'),
('acid blast', 'Usage: cast acid blast\n\nAn area-effect burst of acid damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a decanter of fluorinide hydroxate\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 75%\nClasses: Mage', 'seed'),
('advanced berserking', 'An upgraded berserk with a stronger effect.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 50%\nClasses: Warrior', 'seed'),
('advanced kicking', 'More of your unarmed strikes land as kicks, boosting extra-attack odds.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 25%\nClasses: Monk', 'seed'),
('animate', 'Usage: cast animate [<target>]\n\nAnimates an object to fight for you. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a dragon lich''s tooth\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('arctic blast', 'Usage: cast arctic blast\n\nAn area-effect burst of cold damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: an ice pipe\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 16%\nClasses: Mage', 'seed'),
('armor', 'Usage: pray armor [<target>]\n\nA protective blessing that improves armor class. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('astral walk', 'Usage: pray astral walk [<target>]\n\nTravel the astral plane to another location. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 35\nDiscipline: 33%\nClasses: Cleric', 'seed'),
('atomize', 'Usage: cast atomize [<target>]\n\nAn overwhelming single-target burst of energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a vial of powdered dragon bone\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 80%\nClasses: Mage', 'seed'),
('attune', 'Usage: pray attune [<target>]\n\nBind a holy symbol to your faction. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 10%\nClasses: Cleric', 'seed'),
('backstab', 'A devastating sneak attack against an unaware or from-behind target.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('barehand proficiency', 'Usage: cast barehand proficiency [<target>], pray barehand proficiency [<target>]\n\nBasic proficiency fighting unarmed. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid, Mage', 'seed'),
('barkskin', 'Usage: cast barkskin [<target>]\n\nYour skin turns to bark, granting a strong armor bonus. Targets one person -- you by default, or someone you name.\nRequires: a dollop of petrified syrup\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Druid', 'seed'),
('bash', 'Knock your target down, stunning them briefly.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('beast soother', 'Usage: cast beast soother [<target>]\n\nCalms a hostile or hunting animal. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some cactus pulp\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 6%\nClasses: Druid', 'seed'),
('berserk', 'Forgo defense for a burst of offense -- but you''re much harder to rescue or parry while raging.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('bind', 'Usage: cast bind [<target>]\n\nWebs a target in place. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a black widow''s web\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('blast of fury', 'Usage: cast blast of fury [<target>]\n\nA bolt of raw energy damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: the blood of a scorned woman\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 20%\nClasses: Mage', 'seed'),
('bleed', 'Usage: pray bleed [<target>]\n\nOpens a wound that bleeds over time. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('bless', 'Usage: pray bless [<target>]\n\nA blessing that improves hit and damage rolls. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('blindfighting', 'Reduces the penalty for fighting while blinded.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('blindness', 'Usage: pray blindness [<target>]\n\nBlinds a target. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 21\nDiscipline: 84%\nClasses: Cleric', 'seed'),
('blizzard', 'Usage: cast blizzard\n\nA room-persistent area-effect cold storm. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 39\nDiscipline: 50%\nClasses: Mage', 'seed'),
('blunt proficiency', 'Usage: cast blunt proficiency [<target>], pray blunt proficiency [<target>]\n\nBasic proficiency with blunt weapons. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid, Mage', 'seed'),
('blur', 'A chance at an extra unarmed attack each round while empty-handed.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('bodyslam', 'A grappling throw that slams your opponent down for damage.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 10\nDiscipline: 30%\nClasses: Warrior', 'seed'),
('bone breaker', 'Usage: pray bone breaker [<target>]\n\nBreaks one of a target''s limbs. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 40\nDiscipline: 51%\nClasses: Cleric', 'seed'),
('bonebreak', 'A high-damage grapple attack that breaks a limb.\nUsage: bonebreak (while fighting). Heavy limb damage plus a lasting Broken Bone affliction -- unless the victim knows iron bones.\nRelated: skills practice cast pray affects\nApprox. Level: 50\nDiscipline: 75%\nClasses: Monk', 'seed'),
('bramble drain', 'Usage: cast bramble drain [<target>]\n\nA thorned vine that drains a small amount of life to you. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 3\nClasses: Druid', 'seed'),
('brawl avoidance', 'Passive resistance to grapple- and trip-style attacks.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 75%\nClasses: Warrior', 'seed'),
('call lightning', 'Usage: pray call lightning [<target>]\n\nCalls down a bolt of lightning. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 40\nDiscipline: 51%\nClasses: Cleric', 'seed'),
('calm', 'Usage: cast calm [<target>]\n\nPacifies a target, stopping violence. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: an olive branch\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 58%\nClasses: Mage', 'seed'),
('catfall', 'Halves damage from a fall.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed'),
('catleap', 'Leap and glide a direction, out of combat.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed'),
('chain attack', 'A chance at a bonus follow-up strike each round.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('chain lightning', 'Usage: cast chain lightning [<target>]\n\nA bolt of lightning that arcs between targets. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a tiny glowing spark\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 60%\nClasses: Mage', 'seed'),
('charge stave', 'Usage: cast charge stave [<target>]\n\nCharges a magical stave. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('chi', 'A chi-powered strike against a foe.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed'),
('chop', 'An edge-of-hand strike.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 51%\nClasses: Monk', 'seed'),
('cintai', 'A passive to-hit bonus.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 5%\nClasses: Monk', 'seed'),
('close quarters fighting', 'A combat bonus while grappled or fighting at point-blank range.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 50\nDiscipline: 85%\nClasses: Warrior', 'seed'),
('clot', 'Usage: cast clot [<target>], pray clot [<target>]\n\nStops a victim''s bleeding. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 2\nDiscipline: 16%\nClasses: Cleric, Druid', 'seed'),
('cloud of concealment', 'Usage: cast cloud of concealment [<target>]\n\nFills the room with concealing mist. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a prism of condensation\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 20%\nClasses: Mage', 'seed'),
('color spray', 'Usage: cast color spray\n\nAn area-effect burst of damage that can blind. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a rainbow stone\nRelated: skills practice cast pray affects\nApprox. Level: 12\nDiscipline: 35%\nClasses: Mage', 'seed'),
('concealment', 'Hide your movement trail from trackers. Passive -- while you know it, a mortal's `track` can't follow your trail (it goes cold).\nRequires: passive -- no command to invoke\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('conjure elemental air', 'Usage: cast conjure elemental air [<target>]\n\nSummons an air elemental ally. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some pieces of cloud stone\nRelated: skills practice cast pray affects\nApprox. Level: 12\nDiscipline: 35%\nClasses: Mage', 'seed'),
('conjure elemental earth', 'Usage: cast conjure elemental earth [<target>]\n\nSummons an earth elemental ally. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a piece of lichstone\nRelated: skills practice cast pray affects\nApprox. Level: 21\nDiscipline: 63%\nClasses: Mage', 'seed'),
('conjure elemental fire', 'Usage: cast conjure elemental fire [<target>]\n\nSummons a fire elemental ally. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a star sapphire\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 57%\nClasses: Mage', 'seed'),
('conjure elemental water', 'Usage: cast conjure elemental water [<target>]\n\nSummons a water elemental ally. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a turquoise waterstone\nRelated: skills practice cast pray affects\nApprox. Level: 24\nDiscipline: 71%\nClasses: Mage', 'seed'),
('consecrate', 'Usage: pray consecrate [<target>]\n\nFills the room with a persistent holy effect. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 43\nDiscipline: 60%\nClasses: Cleric', 'seed'),
('copy', 'Usage: cast copy [<target>]\n\nDuplicates an item. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some doppleganger''s skin\nRelated: skills practice cast pray affects\nApprox. Level: 23\nDiscipline: 70%\nClasses: Mage', 'seed'),
('counter move', 'Resist being shoved or thrown out of position.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 50%\nClasses: Monk', 'seed'),
('counter steal', 'A passive chance to catch someone trying to steal from you.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('create food', 'Usage: cast create food [<target>], pray create food [<target>]\n\nConjures food from nothing. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 3\nDiscipline: 11%\nClasses: Cleric, Druid', 'seed'),
('create water', 'Usage: cast create water [<target>], pray create water [<target>]\n\nFills a container with water. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 3\nDiscipline: 11%\nClasses: Cleric, Druid', 'seed'),
('critical hitting', 'Improves your access to the harshest critical-hit outcomes.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('crusade', 'Usage: pray crusade [<target>]\n\nA group-wide blessing for everyone in the room. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 49\nDiscipline: 80%\nClasses: Cleric', 'seed'),
('cudgel', 'A blunt, non-lethal knockout-style attack.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 41\nDiscipline: 66%\nClasses: Thief', 'seed'),
('cure blindness', 'Usage: cast cure blindness [<target>], pray cure blindness [<target>]\n\nRemoves blindness from a victim. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 12\nDiscipline: 45%\nClasses: Cleric, Druid', 'seed'),
('cure disease', 'Usage: cast cure disease [<target>], pray cure disease [<target>]\n\nRemoves disease from a victim. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 8\nDiscipline: 30%\nClasses: Cleric, Druid', 'seed'),
('cure paralysis', 'Usage: pray cure paralysis [<target>]\n\nRemoves paralysis from a victim. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 37\nDiscipline: 40%\nClasses: Cleric', 'seed'),
('cure poison', 'Usage: cast cure poison [<target>], pray cure poison [<target>]\n\nRemoves poison from a victim. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 3\nDiscipline: 11%\nClasses: Cleric, Druid', 'seed'),
('curse', 'Usage: pray curse [<target>]\n\nCurses a target or object. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 13\nDiscipline: 51%\nClasses: Cleric', 'seed'),
('deathstroke', 'A heavy, finishing-style attack against a single target.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 51%\nClasses: Warrior', 'seed'),
('defenestrate', 'Throw a victim through a window into another room.\nUsage: defenestrate (while fighting). A leverage throw that slams your opponent to the ground and costs them a round.\nRelated: skills practice cast pray affects\nApprox. Level: 42\nDiscipline: 50%\nClasses: Monk', 'seed'),
('detect invisibility', 'Usage: cast detect invisibility [<target>]\n\nLets you see invisible things. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: an eclipse heart\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('detect magic', 'Usage: cast detect magic [<target>]\n\nLets you see magical auras. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some athanor dust\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('detect trap', 'Spot a trap before it triggers.\nRequires: not applicable -- this is a real command, see `search`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('devotion', 'Usage: pray devotion [<target>]\n\nPassive prayer-point regeneration. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('disarm', 'Knock the weapon out of an opponent''s hand.\nRequires: not applicable -- this is a real command, see `disarm`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 33%\nClasses: Monk, Thief, Warrior', 'seed'),
('disarm trap', 'Safely disable a trap you''ve detected.\nRequires: not applicable -- this is a real command, see `disarmtrap`\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 33%\nClasses: Thief', 'seed'),
('disguise', 'Alter your apparent identity.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('dispel invisible', 'Usage: cast dispel invisible [<target>]\n\nReveals an invisible target. Strips the AFFECT_INVISIBLE affect from yourself by default, or an ally you name; says so plainly if the target is already visible.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 17\nDiscipline: 50%\nClasses: Mage', 'seed'),
('dispel magic', 'Usage: cast dispel magic [<target>]\n\nStrips magical effects from a being or object. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a white-metal magnet\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 61%\nClasses: Mage', 'seed'),
('divination', 'Usage: cast divination [<target>]\n\nReveals information about an object or being. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a crystal ball\nRelated: skills practice cast pray affects\nApprox. Level: 45\nDiscipline: 68%\nClasses: Mage', 'seed'),
('dodge', 'A passive chance to evade incoming melee attacks; the more you fight, the better you get at it.\nRequires: passive -- no command to invoke\nRelated: skills practice affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('doorbash', 'Charge a closed -- even locked -- door and force it open by brute strength, no key needed. Fail and you bounce off, bruised.\nUsage: doorbash <direction>\nRelated: skills practice open affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('dual wield', 'Passively reduces the damage penalty for your off-hand weapon.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 50%\nClasses: Thief, Warrior', 'seed'),
('dufali', 'Passive resistance to paralysis.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 70%\nClasses: Monk', 'seed'),
('dust storm', 'Usage: cast dust storm\n\nAn area-effect burst of wind and grit damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a decanter of vaporous quartz\nRelated: skills practice cast pray affects\nApprox. Level: 11\nDiscipline: 33%\nClasses: Mage', 'seed'),
('earthmaw', 'Usage: cast earthmaw [<target>]\n\nThe ground splits beneath a target, damaging and knocking them down -- outdoors only. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 41%\nClasses: Druid', 'seed'),
('earthquake', 'Usage: pray earthquake [<target>]\n\nA room-wide tremor that damages everyone in it. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 33\nDiscipline: 26%\nClasses: Cleric', 'seed'),
('energy drain', 'Usage: cast energy drain [<target>]\n\nDrains a resource from a target while damaging them. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the wing of a vampire bat\nRelated: skills practice cast pray affects\nApprox. Level: 36\nDiscipline: 40%\nClasses: Mage', 'seed'),
('enhance weapon', 'Usage: cast enhance weapon [<target>]\n\nPermanently enchants a weapon. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a tiny bag of diamond dust\nRelated: skills practice cast pray affects\nApprox. Level: 24\nDiscipline: 72%\nClasses: Mage', 'seed'),
('ensorcer', 'Usage: cast ensorcer [<target>]\n\nCharms or dominates a target. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a bit of siren''s hair\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 43%\nClasses: Mage', 'seed'),
('entangling roots', 'Usage: cast entangling roots [<target>]\n\nRoots erupt underfoot, tripping and damaging a target -- only works outdoors. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Druid', 'seed'),
('ethereal gate', 'Usage: cast ethereal gate [<target>]\n\nOpens a portal to a named location. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 80%\nClasses: Mage', 'seed'),
('expel', 'Usage: pray expel [<target>]\n\nExpels vermin or a possessing affliction. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 13\nDiscipline: 51%\nClasses: Cleric', 'seed'),
('eyes of Fertuman', 'Usage: cast eyes of Fertuman [<target>]\n\nScries a location by name. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 22\nDiscipline: 65%\nClasses: Mage', 'seed'),
('faerie fire', 'Usage: cast faerie fire [<target>]\n\nMarks a target with a pink aura, easier to hit. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a pixie torch\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 15%\nClasses: Mage', 'seed'),
('faerie fog', 'Usage: cast faerie fog [<target>]\n\nObscures the room in an illusory fog. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a dropper of pixie tears\nRelated: skills practice cast pray affects\nApprox. Level: 18\nDiscipline: 52%\nClasses: Mage', 'seed'),
('falcon wings', 'Usage: cast falcon wings [<target>]\n\nA group buff for flight-like movement. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a green falcon feather\nRelated: skills practice cast pray affects\nApprox. Level: 18\nDiscipline: 53%\nClasses: Mage', 'seed'),
('farlook', 'Usage: cast farlook [<target>]\n\nScries a remote location. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the eyes of an eagle\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 75%\nClasses: Mage', 'seed'),
('fear', 'Usage: cast fear [<target>]\n\nForces a target to flee in terror. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a nightmare''s hoof\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 42%\nClasses: Mage', 'seed'),
('feathery descent', 'Usage: cast feathery descent [<target>]\n\nA group buff that softens falls. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: an orange pigeon feather\nRelated: skills practice cast pray affects\nApprox. Level: 7\nDiscipline: 20%\nClasses: Mage', 'seed'),
('feign death', 'Play dead to avoid detection or attack.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('feral wrath', 'Usage: cast feral wrath [<target>]\n\nSurrender to an animal rage, sharpening your own blows -- a self-only battle-fury boosting your attacks for a short while.\nRequires: a badger''s tooth\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 41%\nClasses: Druid', 'seed'),
('fireball', 'Usage: cast fireball\n\nA powerful area-effect burst of fire damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a vial of red phosphorus\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 40%\nClasses: Mage', 'seed'),
('flamestrike', 'Usage: pray flamestrike [<target>]\n\nA column of divine flame. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 13\nDiscipline: 51%\nClasses: Cleric', 'seed'),
('flaming flesh', 'Usage: cast flaming flesh [<target>]\n\nWreathes you in fire, damaging attackers. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some sulphur paste\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('flaming sword', 'Usage: cast flaming sword [<target>]\n\nImbues a weapon strike with fire damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a phoenix''s claw\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 55%\nClasses: Mage', 'seed'),
('flare', 'Usage: cast flare [<target>]\n\nLights up the room. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a pouch of sodium vapor globes\nRelated: skills practice cast pray affects\nApprox. Level: 3\nDiscipline: 6%\nClasses: Mage', 'seed'),
('flight', 'Usage: cast flight [<target>]\n\nA group buff for true flight. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 34\nDiscipline: 32%\nClasses: Mage', 'seed'),
('focus attack', 'A single concentrated strike for extra damage.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 20%\nClasses: Warrior', 'seed'),
('fortify', 'Sink in behind your shield and brace, cutting incoming damage for a short while. A shield must be equipped.\nUsage: fortify\nRelated: skills practice affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('fumble', 'Usage: cast fumble [<target>]\n\nCauses a target to fumble and disarm themselves. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a jar of whale grease\nRelated: skills practice cast pray affects\nApprox. Level: 42\nDiscipline: 60%\nClasses: Mage', 'seed'),
('galvanize', 'Usage: cast galvanize [<target>]\n\nCharges an item with electricity. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some Promethean fire\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 55%\nClasses: Mage', 'seed'),
('Garmul''s tail', 'Usage: cast Garmul''s tail [<target>]\n\nReduces a target''s mobility in water. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 26\nDiscipline: 5%\nClasses: Mage', 'seed'),
('garrotte', 'Strangle a victim from behind with a cord.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('gills of flesh', 'Usage: cast gills of flesh\n\nA group buff that lets you breathe underwater. Always affects you alone.\nRequires: an unblemished shark''s gill\nRelated: skills practice cast pray affects\nApprox. Level: 9\nDiscipline: 26%\nClasses: Mage', 'seed'),
('granite fists', 'Usage: cast granite fists [<target>]\n\nA stone-infused unarmed strike. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a block of granite\nRelated: skills practice cast pray affects\nApprox. Level: 11\nDiscipline: 31%\nClasses: Mage', 'seed'),
('grapple', 'Grab and hold an opponent, restricting what they can do.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('groundfighting', 'Reduces the penalty for fighting while knocked down.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 10%\nClasses: Monk', 'seed'),
('gusher', 'Usage: cast gusher [<target>]\n\nA bolt of water damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('gust', 'Usage: cast gust [<target>]\n\nA bolt of wind damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a rabbit''s foot on a silver chain\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('hands of flame', 'Usage: cast hands of flame [<target>]\n\nA fiery touch attack. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 4\nDiscipline: 10%\nClasses: Mage', 'seed'),
('harm', 'Usage: pray harm [<target>]\n\nThe strongest bolt of negative energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 41%\nClasses: Cleric', 'seed'),
('harm critical', 'Usage: pray harm critical [<target>]\n\nA powerful bolt of negative energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 56%\nClasses: Cleric', 'seed'),
('harm light', 'Usage: cast harm light [<target>], pray harm light [<target>]\n\nA minor bolt of negative energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid', 'seed'),
('harm serious', 'Usage: pray harm serious [<target>]\n\nA stronger bolt of negative energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 10\nDiscipline: 39%\nClasses: Cleric', 'seed'),
('haste', 'Usage: cast haste [<target>]\n\nA group buff for extra speed and actions. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the hindpaw from a cheetah\nRelated: skills practice cast pray affects\nApprox. Level: 23\nDiscipline: 68%\nClasses: Mage', 'seed'),
('headbutt', 'A headfirst strike -- needs a target roughly your own height.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 41%\nClasses: Warrior', 'seed'),
('heal', 'Usage: cast heal [<target>], pray heal [<target>]\n\nA near-total healing touch. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 17\nDiscipline: 65%\nClasses: Cleric, Druid', 'seed'),
('heal critical', 'Usage: cast heal critical [<target>], pray heal critical [<target>]\n\nA powerful healing touch. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 10\nDiscipline: 76%\nClasses: Cleric, Druid', 'seed'),
('heal critical spray', 'Usage: pray heal critical spray [<target>]\n\nHeals everyone in the room. Targets one person -- you by default, or someone you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 39\nDiscipline: 46%\nClasses: Cleric', 'seed'),
('heal full', 'Usage: pray heal full [<target>]\n\nThe strongest single-target heal. Targets one person -- you by default, or someone you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 12%\nClasses: Cleric', 'seed'),
('heal full spray', 'Usage: pray heal full spray [<target>]\n\nThe strongest area heal, for everyone in the room. Targets one person -- you by default, or someone you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 50\nDiscipline: 84%\nClasses: Cleric', 'seed'),
('heal light', 'Usage: cast heal light [<target>], pray heal light [<target>]\n\nA minor healing touch. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid', 'seed'),
('heal serious', 'Usage: cast heal serious [<target>], pray heal serious [<target>]\n\nA stronger healing touch. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 41%\nClasses: Cleric, Druid', 'seed'),
('heal spray', 'Usage: pray heal spray [<target>]\n\nA strong area heal for everyone in the room. Targets one person -- you by default, or someone you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 43\nDiscipline: 60%\nClasses: Cleric', 'seed'),
('hellfire', 'Usage: cast hellfire\n\nAn area-effect burst of fire damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: some liquid brimstone\nRelated: skills practice cast pray affects\nApprox. Level: 47\nDiscipline: 75%\nClasses: Mage', 'seed'),
('heroes'' feast', 'Usage: pray heroes'' feast [<target>]\n\nA feast that buffs everyone who partakes. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nClasses: Cleric', 'seed'),
('hide', 'Conceal yourself in the room you''re standing in.\nRequires: not applicable -- this is a real command, see `hide`\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 50%\nClasses: Thief', 'seed'),
('hurl', 'Throw a victim bodily out of the room.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('ice storm', 'Usage: cast ice storm\n\nAn area-effect burst of cold damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: an iceberg core\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 58%\nClasses: Mage', 'seed'),
('icy grip', 'Usage: cast icy grip [<target>]\n\nA bolt of cold damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a chunk of dry ice\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 40%\nClasses: Mage', 'seed'),
('identify', 'Usage: cast identify [<target>]\n\nReveals what an item really is. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the lens from a monocle\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 40%\nClasses: Mage', 'seed'),
('illuminate', 'Usage: cast illuminate [<target>]\n\nLights up an object. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a syalime stick\nRelated: skills practice cast pray affects\nApprox. Level: 2\nDiscipline: 3%\nClasses: Mage', 'seed'),
('immobilize', 'Usage: cast immobilize [<target>]\n\nRoots a target in place. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a tiny lasso made of basilisk hair\nRelated: skills practice cast pray affects\nApprox. Level: 36\nDiscipline: 37%\nClasses: Mage', 'seed'),
('infect', 'Usage: pray infect [<target>]\n\nInfects a wound. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 16\nDiscipline: 63%\nClasses: Cleric', 'seed'),
('infravision', 'Usage: cast infravision [<target>]\n\nLets you see in the dark. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a red snake eye\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 10%\nClasses: Mage', 'seed'),
('invisibility', 'Usage: cast invisibility [<target>]\n\nTurns yourself invisible, or an ally you name. Untargetable by name and invisible to the room listing for anyone but an immortal, until it wears off or is dispelled.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 17\nDiscipline: 51%\nClasses: Mage', 'seed'),
('iron bones', 'Resistance to bone-breaking damage.\nPassive. Lets you shrug off a Monk's bonebreak -- the blow lands but the bone won't break.\nRelated: skills practice cast pray affects\nApprox. Level: 38\nDiscipline: 40%\nClasses: Monk', 'seed'),
('iron fist', 'Bonus strength-based damage while your hands are bare.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('iron flesh', 'A passive armor bonus on unequipped body slots.\nPassive. While unarmed, your hardened body is harder to land a clean blow on.\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 20%\nClasses: Monk', 'seed'),
('iron legs', 'Increases your maximum movement points.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 45\nDiscipline: 60%\nClasses: Monk', 'seed'),
('iron muscles', 'A passive strength bonus.\nPassive. A flat bonus to your barehanded damage.\nRelated: skills practice cast pray affects\nApprox. Level: 42\nDiscipline: 50%\nClasses: Monk', 'seed'),
('iron skin', 'Resistance to skin-condition damage effects.\nPassive. Skin like hammered iron cuts a share off every blow you take.\nRelated: skills practice cast pray affects\nApprox. Level: 35\nDiscipline: 30%\nClasses: Monk', 'seed'),
('iron will', 'Resistance to non-magical damage and effects.\nPassive. Your iron will throws off mind-affecting magic -- fear, slumber, and the like.\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 70%\nClasses: Monk', 'seed'),
('jirin', 'Dodge, block, or deflect an incoming unarmed attack.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed'),
('kick', 'An unarmed kick attack.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk, Thief', 'seed'),
('kneestrike', 'A knee strike -- unusable while crawling.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 60%\nClasses: Warrior', 'seed'),
('knit bone', 'Usage: pray knit bone [<target>]\n\nRepairs a broken bone. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 99%\nClasses: Cleric', 'seed'),
('knot', 'Usage: cast knot [<target>]\n\nA powerful self-ward. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 50\nDiscipline: 85%\nClasses: Mage', 'seed'),
('kubo', 'Your unarmed strikes scale with skill and level.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed'),
('lava lance', 'Usage: cast lava lance [<target>]\n\nA devastating single-target bolt of molten rock. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a shard of lava rock\nRelated: skills practice cast pray affects\nApprox. Level: 50\nDiscipline: 86%\nClasses: Mage', 'seed'),
('lava stream', 'Usage: cast lava stream\n\nAn area-effect burst of molten rock damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: an iridescent, volcanic rock\nRelated: skills practice cast pray affects\nApprox. Level: 47\nDiscipline: 75%\nClasses: Mage', 'seed'),
('leeching vine', 'Usage: cast leeching vine [<target>]\n\nA parasitic vine drains a target''s life, damaging them and healing you for part of it.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 48\nClasses: Druid', 'seed'),
('levitate', 'Usage: cast levitate\n\nA buff that lets you float above the ground. Always affects you alone.\nRequires: a bottle of ka\nRelated: skills practice cast pray affects\nApprox. Level: 11\nDiscipline: 32%\nClasses: Mage', 'seed'),
('lightning bolt', 'Usage: cast lightning bolt [<target>]\n\nA bolt of lightning damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 20%\nClasses: Mage', 'seed'),
('mage repair', 'Usage: cast mage repair [<target>]\n\nMagically repairs a piece of equipment. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 17\nDiscipline: 50%\nClasses: Mage', 'seed'),
('mage sight', 'Usage: cast mage sight [<target>]\n\nA bundle of detection senses -- infravision, true sight, and more. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a golden carrot\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('mana', 'Usage: cast mana [<target>]\n\nGoverns the size of your mana pool. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('materialize', 'Usage: cast materialize [<target>]\n\nConjures a named item out of thin air, for a price. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 15%\nClasses: Mage', 'seed'),
('meditate', 'Usage: cast meditate [<target>]\n\nA meditative discipline that helps you recover vitality faster. Restores Vitality -- yourself by default, or an ally you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Druid, Mage', 'seed'),
('meteor swarm', 'Usage: cast meteor swarm [<target>]\n\nA powerful single-target strike from above. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: some pieces of sky rock\nRelated: skills practice cast pray affects\nApprox. Level: 39\nDiscipline: 50%\nClasses: Mage', 'seed'),
('mystic darts', 'Usage: cast mystic darts [<target>]\n\nA bolt of raw magical energy. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 12%\nClasses: Mage', 'seed'),
('nature''s wrath', 'Usage: cast nature''s wrath [<target>]\n\nBeams of raw natural fury tear into a target. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 46\nClasses: Druid', 'seed'),
('numb', 'Usage: pray numb [<target>]\n\nNumbs a limb, reducing what a victim can do with it. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('oomlat', 'A passive armor bonus while fighting unarmed.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Monk', 'seed'),
('paralyze', 'Usage: pray paralyze [<target>]\n\nFully paralyzes a target. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 33\nDiscipline: 26%\nClasses: Cleric', 'seed'),
('paralyze limb', 'Usage: pray paralyze limb [<target>]\n\nParalyzes one of a target''s limbs. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 22\nDiscipline: 86%\nClasses: Cleric', 'seed'),
('parry', 'A passive chance to block an incoming melee attack outright.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('pebble spray', 'Usage: cast pebble spray\n\nAn area-effect burst of earthen damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a bag of perfectly rounded pebbles\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 15%\nClasses: Mage', 'seed'),
('peek', 'Attempt to see what someone is carrying, without their knowledge.\nRequires: not applicable -- this is a real command, see `peek`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Thief', 'seed'),
('penance', 'Usage: pray penance [<target>]\n\nA meditative discipline that helps you recover vitality faster. Restores Vitality -- yourself by default, or an ally you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('pick lock', 'Pick a locked door or container.\nRequires: not applicable -- this is a real command, see `unlock`\nRelated: skills practice cast pray affects\nApprox. Level: 21\nClasses: Thief', 'seed'),
('pierce proficiency', 'Usage: cast pierce proficiency [<target>], pray pierce proficiency [<target>]\n\nBasic proficiency with piercing weapons. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid, Mage', 'seed'),
('pierce resistance', 'Usage: cast pierce resistance [<target>]\n\nPassive resistance to piercing damage. Targets one person -- you by default, or someone you name.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 47\nClasses: Mage', 'seed'),
('pillar of salt', 'Usage: pray pillar of salt [<target>]\n\nA single-target divine damage spell. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('plague of locusts', 'Usage: pray plague of locusts [<target>]\n\nA swarm that damages everyone in the room. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 21\nDiscipline: 81%\nClasses: Cleric', 'seed'),
('plant', 'Surreptitiously plant an item on a victim.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 31\nDiscipline: 50%\nClasses: Thief', 'seed'),
('plasma mirror', 'Usage: cast plasma mirror [<target>]\n\nA reflective shield buff. Targets one person -- you by default, or someone you name.\nRequires: the essence of Solarrius\nRelated: skills practice cast pray affects\nApprox. Level: 34\nDiscipline: 30%\nClasses: Mage', 'seed'),
('poison', 'Usage: pray poison [<target>]\n\nInflicts a poison. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 59%\nClasses: Cleric', 'seed'),
('poison weapon', 'Coat your weapon in poison so your hits inflict it.\nUsage: poison weapon (with a weapon in hand; its hits then have a chance to poison the victim)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Thief', 'seed'),
('polymorph', 'Usage: cast polymorph [<target>]\n\nShapechanges a target into something else. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some skin from a chameleon\nRelated: skills practice cast pray affects\nApprox. Level: 36\nDiscipline: 40%\nClasses: Mage', 'seed'),
('portal', 'Usage: pray portal [<target>]\n\nOpens a portal to a named location. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 49\nDiscipline: 80%\nClasses: Cleric', 'seed'),
('power move', 'Improves your odds of landing a solid, hard-hitting strike.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('powerstone', 'Usage: cast powerstone [<target>]\n\nImbues an item as a mana battery. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a green amethyst\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 55%\nClasses: Mage', 'seed'),
('protection from air', 'Usage: cast protection from air [<target>]\n\nResistance to wind damage. Targets one person -- you by default, or someone you name.\nRequires: a translucent white pebble\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('protection from energy', 'Usage: cast protection from energy [<target>]\n\nResistance to raw energy damage. Targets one person -- you by default, or someone you name.\nRequires: a bright yellow pebble\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('protection from fire', 'Usage: cast protection from fire [<target>]\n\nResistance to fire damage. Targets one person -- you by default, or someone you name.\nRequires: a fiery red pebble\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('protection from water', 'Usage: cast protection from water [<target>]\n\nResistance to water damage. Targets one person -- you by default, or someone you name.\nRequires: a deep blue pebble\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('quivering palm', 'A delayed death-touch strike.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 42\nDiscipline: 51%\nClasses: Monk', 'seed'),
('rain brimstone', 'Usage: pray rain brimstone [<target>]\n\nCalls down a bolt of divine fire. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 18%\nClasses: Cleric', 'seed'),
('rally', 'A battlecry that boosts nearby allies'' combat prowess.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('ranged proficiency', 'Usage: cast ranged proficiency [<target>], pray ranged proficiency [<target>]\n\nBasic proficiency with ranged weapons. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 51%\nClasses: Cleric, Druid, Mage', 'seed'),
('refresh', 'Usage: cast refresh [<target>], pray refresh [<target>]\n\nRestores movement points. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 9\nDiscipline: 1%\nClasses: Cleric, Druid', 'seed'),
('relive', 'Usage: pray relive [<target>]\n\nResurrects a corpse -- requires a holy relic. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 49\nDiscipline: 80%\nClasses: Cleric', 'seed'),
('remove curse', 'Usage: pray remove curse [<target>]\n\nStrips a curse from a person or object. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 7\nDiscipline: 27%\nClasses: Cleric', 'seed'),
('repair', 'Mend damaged equipment yourself -- each repair wears an item down a little for good.\nRequires: not applicable -- this is a real command, see `repair`\nRelated: skills practice cast pray affects\nApprox. Level: 5\nDiscipline: 65%\nClasses: Warrior', 'seed'),
('rescue', 'Swap places with an ally in combat, pulling their attacker onto yourself.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 11%\nClasses: Warrior', 'seed'),
('restore limb', 'Usage: pray restore limb [<target>]\n\nRestores a withered or severed limb. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('retreat', 'Voluntarily disengage from your current opponent.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk, Thief, Warrior', 'seed'),
('riding', 'Mount and control a rideable creature.\nRequires: not applicable -- this is a real command, see `ride`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Cleric, Druid, Mage, Monk, Thief, Warrior', 'seed'),
('riposte', 'A successful parry gives you a chance to counter-attack immediately.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 50%\nClasses: Warrior', 'seed'),
('salve', 'Usage: cast salve [<target>], pray salve [<target>]\n\nTreats a minor wound. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 4\nDiscipline: 11%\nClasses: Cleric, Druid', 'seed'),
('sanctuary', 'Usage: pray sanctuary [<target>]\n\nA strong aura that reduces incoming damage. Targets one person -- you by default, or someone you name.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Cleric', 'seed'),
('sand blast', 'Usage: cast sand blast\n\nAn area-effect burst of earthen damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: some white silicon\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 58%\nClasses: Mage', 'seed'),
('scribe', 'Usage: cast scribe [<target>]\n\nWrites a spell onto a scroll. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('search', 'Find hidden objects or secret exits.\nRequires: not applicable -- this is a real command, see `search`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('second wind', 'Usage: pray second wind [<target>]\n\nRestores a victim''s movement points. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 33\nDiscipline: 26%\nClasses: Cleric', 'seed'),
('sense life', 'Usage: cast sense life [<target>]\n\nDetects living creatures nearby. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some eyes from a blind man\nRelated: skills practice cast pray affects\nApprox. Level: 14\nDiscipline: 40%\nClasses: Mage', 'seed'),
('set trap (arrow)', 'Rig an arrow trap.\nRequires: not applicable -- this is a real command, see `settrap`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Thief', 'seed'),
('set trap (container)', 'Rig a trap on a container.\nRequires: not applicable -- this is a real command, see `settrap`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Thief', 'seed'),
('set trap (door)', 'Rig a trap on a door.\nRequires: not applicable -- this is a real command, see `settrap`\nRelated: skills practice cast pray affects\nApprox. Level: 19\nClasses: Thief', 'seed'),
('set trap (grenade)', 'Rig a grenade-type trap.\nRequires: not applicable -- this is a real command, see `settrap`\nRelated: skills practice cast pray affects\nApprox. Level: 50\nClasses: Thief', 'seed'),
('set trap (mine)', 'Rig a mine-type trap.\nRequires: not applicable -- this is a real command, see `settrap`\nRelated: skills practice cast pray affects\nApprox. Level: 37\nClasses: Thief', 'seed'),
('shatter', 'Usage: cast shatter [<target>]\n\nA destructive shattering attack. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a piece of a banshee''s larynx\nRelated: skills practice cast pray affects\nApprox. Level: 27\nDiscipline: 8%\nClasses: Mage', 'seed'),
('shoulder throw', 'Throw a victim to the ground, damaging and stunning them.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 36\nDiscipline: 35%\nClasses: Monk', 'seed'),
('shove', 'Push an opponent, knocking them off balance.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 33%\nClasses: Warrior', 'seed'),
('sign', 'Communicate silently with hand signals -- only fellow signers understand you.\nRequires: not applicable -- this is a real command, see `sign`\nRelated: skills practice cast pray affects\nApprox. Level: 10\nDiscipline: 26%\nClasses: Cleric, Druid, Mage, Monk, Thief, Warrior', 'seed'),
('silence', 'Usage: cast silence [<target>]\n\nMutes a target, blocking their spellcasting. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the tongue of a screaming baby\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 80%\nClasses: Mage', 'seed'),
('skulk', 'Move from room to room while remaining hidden.\nUsage: skulk (a toggle; while skulking an aggressive monster won''t start a fight with you)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('sky spirit', 'Usage: cast sky spirit [<target>]\n\nSummons a phantasmal bird spirit to strike a target -- scales with your skill. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a pouch of dandelion seeds\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 41%\nClasses: Druid', 'seed'),
('slam', 'A heavy shield-and-body slam for extra damage and a stun.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 50%\nClasses: Warrior', 'seed'),
('slash proficiency', 'Usage: cast slash proficiency [<target>], pray slash proficiency [<target>]\n\nBasic proficiency with slashing weapons. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Cleric, Druid, Mage', 'seed'),
('sling shot', 'Usage: cast sling shot [<target>]\n\nA bolt of earthen damage. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('slumber', 'Usage: cast slumber [<target>]\n\nPuts a target to sleep. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a bag of pixie dust\nRelated: skills practice cast pray affects\nApprox. Level: 13\nDiscipline: 39%\nClasses: Mage', 'seed'),
('sneak', 'Move around without waking sleepers or drawing attention.\nRequires: not applicable -- this is a real command, see `sneak`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('snofalte', 'A mental discipline that can suppress your own bleeding.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 38\nDiscipline: 40%\nClasses: Monk', 'seed'),
('sorcerer''s globe', 'Usage: cast sorcerer''s globe [<target>]\n\nA magical shield that buffs the group''s defense. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: an air daemon''s tail\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Mage', 'seed'),
('spin', 'A spinning grapple-style strike -- needs a free hand.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 17\nDiscipline: 45%\nClasses: Warrior', 'seed'),
('spontaneous combust', 'Usage: pray spontaneous combust [<target>]\n\nSets a target ablaze from within. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 76%\nClasses: Cleric', 'seed'),
('spontaneous generation', 'Usage: cast spontaneous generation [<target>]\n\nConjures raw material by name, for a price. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 32\nDiscipline: 25%\nClasses: Mage', 'seed'),
('springleap', 'Spring instantly from sitting or resting to standing.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 20\nDiscipline: 20%\nClasses: Monk', 'seed'),
('spy', 'Covertly watch a room from elsewhere.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 38\nDiscipline: 61%\nClasses: Thief', 'seed'),
('stabbing', 'A piercing-weapon melee attack.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nClasses: Thief', 'seed'),
('steal', 'Pick a victim''s pocket.\nRequires: not applicable -- this is a real command, see `steal`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Thief', 'seed'),
('stealth', 'Usage: cast stealth [<target>]\n\nA group buff for moving quietly. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a dryad''s footprint\nRelated: skills practice cast pray affects\nApprox. Level: 16\nDiscipline: 47%\nClasses: Mage', 'seed'),
('stone skin', 'Usage: cast stone skin [<target>]\n\nA buff that reduces incoming damage. Targets one person -- you by default, or someone you name.\nRequires: some porous bedrock\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('storm call', 'Usage: cast storm call [<target>]\n\nCalls down lightning or hail -- only works in the right weather. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 23\nClasses: Druid', 'seed'),
('stunning arrow', 'Usage: cast stunning arrow [<target>]\n\nA magical arrow that damages and stuns. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: an eel''s tail\nRelated: skills practice cast pray affects\nApprox. Level: 12\nDiscipline: 34%\nClasses: Mage', 'seed'),
('subterfuge', 'Deceive or redirect an opponent mid-combat.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 41%\nClasses: Thief', 'seed'),
('suffocate', 'Usage: cast suffocate [<target>]\n\nDeprives a target of air. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a glop of cat''s breath\nRelated: skills practice cast pray affects\nApprox. Level: 42\nDiscipline: 60%\nClasses: Mage', 'seed'),
('summon', 'Usage: pray summon [<target>]\n\nTeleports a target to you. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 76%\nClasses: Cleric', 'seed'),
('sunscald', 'Usage: cast sunscald [<target>]\n\nSears a target with a searing lance of focused sunlight, dealing radiant damage.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 16\nClasses: Druid', 'seed'),
('switch opponents', 'Change which opponent you''re actively fighting.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 21%\nClasses: Monk, Thief, Warrior', 'seed'),
('taunt', 'Provoke a target into focusing their aggression on you.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 22\nClasses: Warrior', 'seed'),
('telepathy', 'Usage: cast telepathy [<target>]\n\nSends a message across any distance. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a bit of brain coral\nRelated: skills practice cast pray affects\nApprox. Level: 16\nDiscipline: 47%\nClasses: Mage', 'seed'),
('teleport', 'Usage: cast teleport [<target>]\n\nTeleports you to a random or chosen location. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a piece of brain from an addled man\nRelated: skills practice cast pray affects\nApprox. Level: 19\nDiscipline: 58%\nClasses: Mage', 'seed'),
('thorn barrage', 'Usage: cast thorn barrage [<target>]\n\nSeveral beams of thorny energy lash the target. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 10\nClasses: Druid', 'seed'),
('throatslit', 'A lethal sneak attack targeting the throat.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Thief', 'seed'),
('tornado', 'Usage: cast tornado\n\nAn area-effect burst of wind damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a small vial of wind\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 43%\nClasses: Mage', 'seed'),
('track', 'Follow a target''s trail between rooms.\nUsage: track <name> (points you one step toward your quarry)\nRelated: skills practice cast pray affects\nApprox. Level: 13\nDiscipline: 27%\nClasses: Thief', 'seed'),
('trail seek', 'Usage: cast trail seek [<target>]\n\nTracks a target''s trail. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: the nose of a bloodhound\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Mage', 'seed'),
('trance of blades', 'A defensive stance that sharpens your reflexes at the cost of offense.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nClasses: Warrior', 'seed'),
('tree walk', 'Usage: cast tree walk [<target>]\n\nStep into one tree and out of another far away -- a random self-teleport across the world.\nRequires: some root of the nevthy tree\nRelated: skills practice cast pray affects\nApprox. Level: 41\nDiscipline: 66%\nClasses: Druid', 'seed'),
('trip', 'Knock an opponent to the ground.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Warrior', 'seed'),
('true sight', 'Usage: cast true sight [<target>]\n\nSees through illusions and disguises. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 28\nDiscipline: 11%\nClasses: Mage', 'seed'),
('tsunami', 'Usage: cast tsunami\n\nAn area-effect wave of water damage. This is an area-effect spell -- it strikes everyone else in the room at once, not a single target.\nRequires: a vial of wavetip\nRelated: skills practice cast pray affects\nApprox. Level: 39\nDiscipline: 50%\nClasses: Mage', 'seed'),
('two-handed specialization', 'Bonus damage while wielding a two-handed weapon.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 1\nClasses: Warrior', 'seed'),
('voplat', 'Makes your unarmed damage magical.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('watery grave', 'Usage: cast watery grave [<target>]\n\nA drowning attack against a single target. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: some withered jetsam\nRelated: skills practice cast pray affects\nApprox. Level: 32\nDiscipline: 25%\nClasses: Mage', 'seed'),
('wave crash', 'Usage: cast wave crash [<target>]\n\nA crashing wall of water bursts across the room, damaging every enemy nearby.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 32\nClasses: Druid', 'seed'),
('weapon retention', 'A passive chance to keep your grip on your weapon when disarmed or fumbling.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 75%\nClasses: Warrior', 'seed'),
('whirlwind', 'A spinning attack that can strike every opponent in the room.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 60%\nClasses: Warrior', 'seed'),
('wild agony', 'Usage: cast wild agony [<target>]\n\nInflicts a burst of raw, unnatural pain. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 38\nClasses: Druid', 'seed'),
('wildfire', 'Usage: cast wildfire [<target>]\n\nAn intense, heavy burst of flame. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 48\nClasses: Druid', 'seed'),
('wither limb', 'Usage: pray wither limb [<target>]\n\nWithers one of a target''s limbs. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 48\nDiscipline: 76%\nClasses: Cleric', 'seed'),
('withering touch', 'Usage: cast withering touch [<target>]\n\nA necrotic touch that damages a victim and leaves their flesh rotting for several rounds.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 32\nClasses: Druid', 'seed'),
('wizardry', 'Usage: cast wizardry [<target>]\n\nThe core skill of casting itself. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Mage', 'seed'),
('wohlin meditation', 'While meditating, unlocks bonus self-cure effects.\nRequires: nothing yet -- not implemented as a command\nRelated: skills practice cast pray affects\nApprox. Level: 25\nDiscipline: 1%\nClasses: Monk', 'seed'),
('word of recall', 'Usage: cast word of recall [<target>], pray word of recall [<target>]\n\nTeleports yourself or an ally to the recall point. Not yet wired to a real effect -- consumes its component/symbol and does nothing further yet.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`); a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 21\nDiscipline: 83%\nClasses: Cleric, Druid', 'seed'),
('yoginsa', 'Usage: yoginsa\n\nMeditate to recover HP and Vitality faster -- sits you down automatically if you were standing. Not usable while fighting.\nRequires: not applicable -- this is a real command, see `yoginsa`\nRelated: skills practice cast pray affects\nApprox. Level: 1\nDiscipline: 1%\nClasses: Monk', 'seed')
ON DUPLICATE KEY UPDATE `body` = IF(`updated_by` = 'seed', VALUES(`body`), `body`);
-- topic entirely (2026-08-05 TODO follow-up: 'players currently only
-- discover you need a component/holy symbol by trying to cast and
-- getting refused' -- turned out the underlying help_topic generator
-- system already existed since 2026-07-22 above, but these six were
-- added to skill.c's roster afterward and never got a matching row).
-- Same hand-authored format/conventions as the generated rows above --
-- Requires/Approx. Level/Discipline sourced the same way (skill.c for
-- level/classes, sneezymud-master/code/code/misc/spell_info.cc's real
-- discArray[] START_ values for Discipline where a real upstream entry
-- exists; protection from earth/inferno/sterilize/stupidity all have
-- one, summon swarm/animal companion are Tobin-original mechanics with
-- no upstream spellInfo entry to cite, so their Discipline line is
-- omitted, same precedent the generator itself used).
INSERT INTO `help_topic` (`name`, `body`, `updated_by`) VALUES
('protection from earth', 'Usage: cast protection from earth\n\nWards the room against earthen harm. This is a room-wide effect -- everyone present is warded, not just a chosen target.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 8\nDiscipline: 1%\nClasses: Mage', 'seed'),
('inferno', 'Usage: cast inferno [<target>]\n\nA burning attack that scorches a single target. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 21\nDiscipline: 15%\nClasses: Mage', 'seed'),
('stupidity', 'Usage: cast stupidity [<target>]\n\nAddles a target''s mind, dulling their intelligence for a while. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 15\nDiscipline: 15%\nClasses: Druid', 'seed'),
('sterilize', 'Usage: pray sterilize [<target>]\n\nCures a festering infection. This is a single-target spell -- aimed at one person: whoever you name, or whoever you''re already fighting if you don''t name anyone.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 6\nDiscipline: 21%\nClasses: Cleric', 'seed'),
('summon swarm', 'Usage: pray summon swarm\n\nSummons a swarm of locusts to fight at your side. This is a self-cast effect -- no target needed.\nRequires: a holy symbol -- any item keyworded "symbol" (e.g., a wooden holy symbol) (`pray`)\nRelated: skills practice cast pray affects\nApprox. Level: 30\nClasses: Cleric', 'seed'),
('animal companion', 'Usage: cast animal companion\n\nCalls a loyal beast companion to your side. This is a self-cast effect -- no target needed.\nRequires: any item keyworded "component" (e.g., a pouch of spell components) (`cast`)\nRelated: skills practice cast pray affects\nApprox. Level: 24\nClasses: Druid', 'seed')
ON DUPLICATE KEY UPDATE `body` = IF(`updated_by` = 'seed', VALUES(`body`), `body`);
INSERT INTO help_topic (name, body, updated_by) VALUES
('death mist',
 'Usage: cast death mist\n\nA high Druid working of rot and plague. You breathe out a chilling green mist that rolls across the whole room, infecting every creature caught in it -- friend and foe alike, save your own groupmates -- with a wasting syphilitic sickness that saps their health over time. Handle it with care: some of the mist can curl back over you and leave you infected as well. Ported from real SneezyMUD''s Shaman death mist, folded onto the Druid.\nRelated: cure disease creeping doom\nApprox. Level: 45\nClasses: Druid',
 'system')
ON DUPLICATE KEY UPDATE body=VALUES(body), updated_by=VALUES(updated_by);
