/*******************************************************************
 * TobinMUD ver. 0.1 - All rights reserved                         *
 * The TobinMUD Development Team                                   *
 *******************************************************************/
#ifndef TOBIN_OBJ_PLANT_H
#define TOBIN_OBJ_PLANT_H

#include <stdbool.h>

struct room;
struct obj;

/* Seed farming (Planting, Sneezy → Tobin feature audit) -- ported from the
 * real `obj_plant.cc`/`obj_plant.h` (TPlant) and `task_plant.cc`. Reuses
 * obj.h's existing generic 4-int `val[]` payload for TPlant's own four
 * fields (planttype/plantage/plantyield/verminated), rather than adding a
 * dedicated struct -- a plant is an ordinary obj_t (category OBJ_CAT_OTHER,
 * raw_type OBJ_PLANT_RAW_TYPE) whose short/long descr get regenerated by
 * obj_plant_refresh_desc() as it ages, same pattern obj.c's obj_grow_pool()
 * already uses for pee/blood pools.
 *
 * Disclosed simplification: the original's real per-type lifespans run
 * 6 months to 15 real years (its own comment: "an average of 2 age points
 * per mud hour"). At that scale nobody would ever see a plant finish
 * growing in a normal session, so lifespans here are compressed into tens/
 * hundreds of growth ticks (~1 real minute each, obj_plant_growth_tick()
 * below) while preserving the ORIGINAL's fast/slow ordering (a candy heart
 * tree still withers far faster than a rose bush). Also simplified: fruit
 * drops onto the room floor next to the plant rather than into it as a
 * container (Tobin's flatter object model has no "look in <plant>" get-
 * from-container step); no mob-spawning "candy tree attracts vermin"
 * sub-feature (commented out even in the reference source); TPlant's
 * peeOnMe() override exists in obj_plant.h but was never actually defined
 * in the reference clone's obj_plant.cc -- dropped here as vestigial,
 * not silently lost real behavior. */

/* Matches obj.h's `raw_type` field -- the original's real ITEM_PLANT
 * (itemTypeT) value, verbatim. */
#define OBJ_PLANT_RAW_TYPE 59

/* 15 real plant types, Sneezy's own seed_to_plant() order (obj_plant.cc)
 * verbatim -- index 0-14 IS `val[0]` (planttype). Type 11 is displayed as
 * "pot" rather than the original's literal "marijuana", matching Tobin's
 * own already-shipped drug-naming convention (drug.c's DRUG_POT) and the
 * real seeded item's own short_desc ("swamp weed"). */
#define PLANT_TYPE_COUNT 15

/* True iff `seed_vnum` is one of the 15 real seed-sack vnums; writes the
 * plant type index (0-14) to *out_type. False (leaves *out_type
 * untouched) for anything else. */
bool plant_type_for_seed_vnum(int seed_vnum, int *out_type);

/* Real fruit-object vnum this plant type yields once mature (verbatim
 * from the original's plantfruits[]). */
int plant_fruit_vnum(int type);

/* Spawns a fresh, brand-new (age 0) plant obj_t of `type` and attaches it
 * to `room` -- caller has already verified room_can_plant()/the 8-per-room
 * cap. Mirrors task_plant()'s CMD_TASK completion step (reads the generic
 * plant prototype, sets its type, calls updateDesc()). */
void obj_plant_create(struct room *room, int type);

/* Regenerates `o`'s name/short_descr/long_descr from its current val[]
 * state (obj_plant_refresh_desc()'s own stage table, ported verbatim from
 * TPlant::updateDesc()'s plantkeywords/plantname/plantdesc/planttypes
 * arrays) -- dirt mound -> sprout -> small -> mature -> withered. Public
 * so obj_plant_create() and the growth tick share one implementation. */
void obj_plant_refresh_desc(struct obj *o);

/* Ages every plant sitting directly in a room by a small random amount,
 * occasionally dropping a fruit object next to a mature/withered one
 * (or losing it to vermin instead -- val[3]/verminated), and marks a
 * plant past its lifespan for cleanup via the EXISTING obj_decay_tick()
 * machinery (sets decay_time rather than destroying it directly here) --
 * pulse-registered in main.c (~60s cadence, same as obj_pool_decay_tick()/
 * obj_decay_tick() themselves) and also forced by `aitick` for
 * deterministic testing. */
void obj_plant_growth_tick(long pulse_num);

#endif
