#!/usr/bin/env python3
"""Convert the upstream DikuMUD-style zonefiles (one file per zone, under
`sneezymud-master/lib/zonefiles/<zonenum>`) into a single SQL seed for
Tobin's `zone_reset` table, so the whole zone-reset system is DB-driven like
everything else (the `zone` metadata table already lives in the DB; only the
reset COMMANDS were still file-based).

Each command line is `<CMD> <if_flag> <arg1> <arg2> <arg3> [comment]`, e.g.
  M 0 560 1 566   Plump Cat (pet)      -> load mob 560 (max 1) into room 566
  O 0 15315 1 433 trophy board         -> load obj into room
  G 1 10519 1                          -> give last-loaded mob obj 10519
  E 1 1092 999 1  Granite Ring         -> equip last mob, wear slot 1
  P ...                                -> put obj in obj
  D 0 336 3 1                          -> set door state (room, dir, state)
The `#N` header, the `name~` line, the numeric zone-header line, `*` comments,
and the trailing `S`/`$` are skipped. Sneezy's `?`-conditional and other
non-single-letter opcodes are skipped (not ported yet -- noted on stderr).

    python3 import-zones.py <zonefiles-dir>  > zone_reset.sql
"""
import os
import re
import sys

zonedir = sys.argv[1] if len(sys.argv) > 1 else "sneezymud-master/lib/zonefiles"

rows = []          # (zone_nr, cmd_no, cmd, if_flag, a1, a2, a3, a4, comment)
skipped_ops = {}   # opcode -> count, for the stderr summary


def sql_escape(s):
    return s.replace("\\", "\\\\").replace("'", "''")


for fn in sorted(os.listdir(zonedir), key=lambda x: (not x.isdigit(), int(x) if x.isdigit() else 0)):
    path = os.path.join(zonedir, fn)
    if not os.path.isfile(path):
        continue
    zone_nr = None
    cmd_no = 0
    seen_name = False
    seen_header = False
    with open(path, errors="replace") as f:
        for raw in f:
            line = raw.replace("\r", "").replace("\n", "").strip()
            if not line or line.startswith("*"):
                continue
            if line.startswith("#"):
                m = re.match(r"#\s*(\d+)", line)
                zone_nr = int(m.group(1)) if m else None
                cmd_no = 0
                seen_name = seen_header = False
                continue
            if zone_nr is None:
                continue
            if line == "S" or line.startswith("$"):
                continue
            if not seen_name and line.endswith("~"):
                seen_name = True
                continue
            # The numeric zone-header line (top/lifespan/reset_mode/...) -- the
            # first all-numeric line after the name; its data is already in the
            # `zone` table, so skip it.
            if not seen_header and (line[0].isdigit() or line[0] == "-"):
                seen_header = True
                continue
            tok = line.split()
            cmd = tok[0]
            if len(cmd) != 1 or not cmd.isalpha():
                skipped_ops[cmd] = skipped_ops.get(cmd, 0) + 1
                continue
            cmd = cmd.upper()
            ints = []
            ci = 1
            while ci < len(tok):
                try:
                    ints.append(int(tok[ci]))
                    ci += 1
                except ValueError:
                    break
            comment = " ".join(tok[ci:])[:250]

            def arg(i):
                return ints[i] if i < len(ints) else 0
            rows.append((zone_nr, cmd_no, cmd, arg(0), arg(1), arg(2),
                         arg(3), arg(4), comment))
            cmd_no += 1

out = sys.stdout.write
out("-- GENERATED by db/import-zones.py from the upstream zonefiles.\n")
out("-- Do not edit by hand -- regenerate if the zonefiles change.\n")
out("-- Tobin's DB-driven zone reset commands (one row per reset op).\n\n")
out("CREATE TABLE IF NOT EXISTS `zone_reset` (\n"
    "  `zone_nr` int NOT NULL,\n"
    "  `cmd_no` int NOT NULL,\n"
    "  `command` char(1) NOT NULL,\n"
    "  `if_flag` int NOT NULL DEFAULT 0,\n"
    "  `arg1` int NOT NULL DEFAULT 0,\n"
    "  `arg2` int NOT NULL DEFAULT 0,\n"
    "  `arg3` int NOT NULL DEFAULT 0,\n"
    "  `arg4` int NOT NULL DEFAULT 0,\n"
    "  `comment` varchar(255) NOT NULL DEFAULT '',\n"
    "  PRIMARY KEY (`zone_nr`, `cmd_no`)\n"
    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n")
out("DELETE FROM `zone_reset`;\n")

BATCH = 200
for i in range(0, len(rows), BATCH):
    chunk = rows[i:i + BATCH]
    out("INSERT INTO `zone_reset` (`zone_nr`,`cmd_no`,`command`,`if_flag`,"
        "`arg1`,`arg2`,`arg3`,`arg4`,`comment`) VALUES\n")
    vals = []
    for (z, c, cmd, iff, a1, a2, a3, a4, com) in chunk:
        vals.append(f"({z},{c},'{cmd}',{iff},{a1},{a2},{a3},{a4},'{sql_escape(com)}')")
    out(",\n".join(vals) + ";\n")

sys.stderr.write(f"zone_reset: {len(rows)} reset commands across the zonefiles.\n")
if skipped_ops:
    sys.stderr.write("skipped non-single-letter opcodes: "
                     + ", ".join(f"{k}x{v}" for k, v in sorted(skipped_ops.items())) + "\n")
